/***********************************************************************/
/******************* This file is generated by *************************/
/******************* the Compose Generator *****************************/
/***********************************************************************/

#ifndef __COMPOSE_H__
#define __COMPOSE_H__

#include "NeoIncludes.h"
#include <assert.h>

/*
 * The tree is static, therefore no methods for removing/adding elements,
 * to not make life too complicated, this file is generated by a script.
 * 
 * The implementation with bit fields and unions is not the most pretty one
 * but the most memory efficient.
 * 
 * Payload is either pointing to next node or contains unicode symbol.
 * indication what is inside is given by the isLeaf flag cast to uint16_t
 * in Initialization only to trick the compiler, as only first element of the
 * union can be initialized. 
*/

struct LayeredKey {
	uint8_t layer;
	uint8_t key;
};

struct Node {
	struct {
		uint8_t isLastElement : 1;
		uint8_t isLeaf : 1;
		uint8_t layer : 6;
		uint8_t keycode : 8;
	} layeredKey;
	union {
		uint16_t unicode;
		Node* nodes;
	} payload;
};


class Compose
{
	private:
	Node* currentNode;

	const static Node root[] PROGMEM;
	const static Node NODE_1314732443264[] PROGMEM;
	const static Node NODE_1314732958528[] PROGMEM;
	const static Node NODE_1314733082880[] PROGMEM;
	const static Node NODE_1314733083040[] PROGMEM;
	const static Node NODE_1314733086960[] PROGMEM;
	const static Node NODE_1314733087120[] PROGMEM;
	const static Node NODE_1314733087680[] PROGMEM;
	const static Node NODE_1314733087840[] PROGMEM;
	const static Node NODE_1314733170400[] PROGMEM;
	const static Node NODE_1314733170560[] PROGMEM;
	const static Node NODE_1314733173600[] PROGMEM;
	const static Node NODE_1314733174000[] PROGMEM;
	const static Node NODE_1314733174480[] PROGMEM;
	const static Node NODE_1314733174800[] PROGMEM;
	const static Node NODE_1314733175040[] PROGMEM;
	const static Node NODE_1314733175200[] PROGMEM;
	const static Node NODE_1314733176480[] PROGMEM;
	const static Node NODE_1314733176640[] PROGMEM;
	const static Node NODE_1314733177280[] PROGMEM;
	const static Node NODE_1314733177840[] PROGMEM;
	const static Node NODE_1314733178240[] PROGMEM;
	const static Node NODE_1314733178320[] PROGMEM;
	const static Node NODE_1314733170480[] PROGMEM;
	const static Node NODE_1314733176320[] PROGMEM;
	const static Node NODE_1314733176720[] PROGMEM;
	const static Node NODE_1314733173840[] PROGMEM;
	const static Node NODE_1314733176400[] PROGMEM;
	const static Node NODE_1314733174560[] PROGMEM;
	const static Node NODE_1314734293216[] PROGMEM;
	const static Node NODE_1314734293536[] PROGMEM;
	const static Node NODE_1314733177040[] PROGMEM;
	const static Node NODE_1314732442384[] PROGMEM;
	const static Node NODE_1314732700304[] PROGMEM;
	const static Node NODE_1314732700544[] PROGMEM;
	const static Node NODE_1314732700704[] PROGMEM;
	const static Node NODE_1314733164160[] PROGMEM;
	const static Node NODE_1314733164320[] PROGMEM;
	const static Node NODE_1314732878048[] PROGMEM;
	const static Node NODE_1314732442704[] PROGMEM;
	const static Node NODE_1314732883488[] PROGMEM;
	const static Node NODE_1314732959808[] PROGMEM;
	const static Node NODE_1314732442864[] PROGMEM;
	const static Node NODE_1314732693904[] PROGMEM;
	const static Node NODE_1314732698304[] PROGMEM;
	const static Node NODE_1314732698544[] PROGMEM;
	const static Node NODE_1314732698464[] PROGMEM;
	const static Node NODE_1314732877728[] PROGMEM;
	const static Node NODE_1314732880208[] PROGMEM;
	const static Node NODE_1314732882288[] PROGMEM;
	const static Node NODE_1314732883248[] PROGMEM;
	const static Node NODE_1314732951968[] PROGMEM;
	const static Node NODE_1314732957648[] PROGMEM;
	const static Node NODE_1314732958768[] PROGMEM;
	const static Node NODE_1314732962768[] PROGMEM;
	const static Node NODE_1314733015344[] PROGMEM;
	const static Node NODE_1314733015504[] PROGMEM;
	const static Node NODE_1314732443424[] PROGMEM;
	const static Node NODE_1314732878528[] PROGMEM;
	const static Node NODE_1314732883008[] PROGMEM;
	const static Node NODE_1314732957728[] PROGMEM;
	const static Node NODE_1314732959088[] PROGMEM;
	const static Node NODE_1314732963008[] PROGMEM;
	const static Node NODE_1314733015104[] PROGMEM;
	const static Node NODE_1314733015184[] PROGMEM;
	const static Node NODE_1314732443504[] PROGMEM;
	const static Node NODE_1314732443744[] PROGMEM;
	const static Node NODE_1314732443904[] PROGMEM;
	const static Node NODE_1314732446304[] PROGMEM;
	const static Node NODE_1314732640832[] PROGMEM;
	const static Node NODE_1314732812752[] PROGMEM;
	const static Node NODE_1314732812992[] PROGMEM;
	const static Node NODE_1314732813632[] PROGMEM;
	const static Node NODE_1314732813712[] PROGMEM;
	const static Node NODE_1314732814032[] PROGMEM;
	const static Node NODE_1314733164240[] PROGMEM;
	const static Node NODE_1314733164560[] PROGMEM;
	const static Node NODE_1314733167440[] PROGMEM;
	const static Node NODE_1314733169680[] PROGMEM;
	const static Node NODE_1314734293456[] PROGMEM;
	const static Node NODE_1314734453072[] PROGMEM;
	const static Node NODE_1314733171040[] PROGMEM;
	const static Node NODE_1314733171280[] PROGMEM;
	const static Node NODE_1314733171520[] PROGMEM;
	const static Node NODE_1314734371232[] PROGMEM;
	const static Node NODE_1314732443824[] PROGMEM;
	const static Node NODE_1314732953888[] PROGMEM;
	const static Node NODE_1314732954128[] PROGMEM;
	const static Node NODE_1314733028784[] PROGMEM;
	const static Node NODE_1314733028944[] PROGMEM;
	const static Node NODE_1314734302096[] PROGMEM;
	const static Node NODE_1314732444144[] PROGMEM;
	const static Node NODE_1314734299936[] PROGMEM;
	const static Node NODE_1314734300336[] PROGMEM;
	const static Node NODE_1314734441152[] PROGMEM;
	const static Node NODE_1314732444304[] PROGMEM;
	const static Node NODE_1314732958288[] PROGMEM;
	const static Node NODE_1314732959568[] PROGMEM;
	const static Node NODE_1314732963328[] PROGMEM;
	const static Node NODE_1314733015664[] PROGMEM;
	const static Node NODE_1314733015824[] PROGMEM;
	const static Node NODE_1314733021424[] PROGMEM;
	const static Node NODE_1314734440832[] PROGMEM;
	const static Node NODE_1314732444624[] PROGMEM;
	const static Node NODE_1314732691184[] PROGMEM;
	const static Node NODE_1314732697984[] PROGMEM;
	const static Node NODE_1314732698144[] PROGMEM;
	const static Node NODE_1314732698064[] PROGMEM;
	const static Node NODE_1314732877248[] PROGMEM;
	const static Node NODE_1314732879088[] PROGMEM;
	const static Node NODE_1314732881168[] PROGMEM;
	const static Node NODE_1314732950928[] PROGMEM;
	const static Node NODE_1314734451952[] PROGMEM;
	const static Node NODE_1314732445264[] PROGMEM;
	const static Node NODE_1314732952208[] PROGMEM;
	const static Node NODE_1314732954848[] PROGMEM;
	const static Node NODE_1314732445584[] PROGMEM;
	const static Node NODE_1314732880528[] PROGMEM;
	const static Node NODE_1314733095040[] PROGMEM;
	const static Node NODE_1314733095200[] PROGMEM;
	const static Node NODE_1314733163680[] PROGMEM;
	const static Node NODE_1314733167360[] PROGMEM;
	const static Node NODE_1314734364192[] PROGMEM;
	const static Node NODE_1314734365872[] PROGMEM;
	const static Node NODE_1314734366032[] PROGMEM;
	const static Node NODE_1314734366192[] PROGMEM;
	const static Node NODE_1314734366432[] PROGMEM;
	const static Node NODE_1314734366592[] PROGMEM;
	const static Node NODE_1314733095680[] PROGMEM;
	const static Node NODE_1314733096400[] PROGMEM;
	const static Node NODE_1314733167200[] PROGMEM;
	const static Node NODE_1314733167680[] PROGMEM;
	const static Node NODE_1314733167920[] PROGMEM;
	const static Node NODE_1314732446144[] PROGMEM;
	const static Node NODE_1314732445904[] PROGMEM;
	const static Node NODE_1314732958048[] PROGMEM;
	const static Node NODE_1314732959328[] PROGMEM;
	const static Node NODE_1314732963248[] PROGMEM;
	const static Node NODE_1314734293696[] PROGMEM;
	const static Node NODE_1314732445744[] PROGMEM;
	const static Node NODE_1314734293856[] PROGMEM;
	const static Node NODE_1314734294176[] PROGMEM;
	const static Node NODE_1314732446544[] PROGMEM;
	const static Node NODE_1314733089280[] PROGMEM;
	const static Node NODE_1314733089440[] PROGMEM;
	const static Node NODE_1314733092000[] PROGMEM;
	const static Node NODE_1314734370752[] PROGMEM;
	const static Node NODE_1314734370992[] PROGMEM;
	const static Node NODE_1314734371312[] PROGMEM;
	const static Node NODE_1314734371472[] PROGMEM;
	const static Node NODE_1314733092880[] PROGMEM;
	const static Node NODE_1314733095760[] PROGMEM;
	const static Node NODE_1314732641952[] PROGMEM;
	const static Node NODE_1314732963728[] PROGMEM;
	const static Node NODE_1314732641552[] PROGMEM;
	const static Node NODE_1314732641392[] PROGMEM;
	const static Node NODE_1314732810352[] PROGMEM;
	const static Node NODE_1314734300176[] PROGMEM;
	const static Node NODE_1314734300496[] PROGMEM;
	const static Node NODE_1314732638992[] PROGMEM;
	const static Node NODE_1314734371952[] PROGMEM;
	const static Node NODE_1314734372192[] PROGMEM;
	const static Node NODE_1314734372432[] PROGMEM;
	const static Node NODE_1314734372672[] PROGMEM;
	const static Node NODE_1314734372752[] PROGMEM;
	const static Node NODE_1314732689104[] PROGMEM;
	const static Node NODE_1314733171840[] PROGMEM;
	const static Node NODE_1314733172560[] PROGMEM;
	const static Node NODE_1314732689344[] PROGMEM;
	const static Node NODE_1314732693184[] PROGMEM;
	const static Node NODE_1314733029104[] PROGMEM;
	const static Node NODE_1314733096480[] PROGMEM;
	const static Node NODE_1314732695024[] PROGMEM;
	const static Node NODE_1314732695184[] PROGMEM;
	const static Node NODE_1314734303856[] PROGMEM;
	const static Node NODE_1314734448352[] PROGMEM;
	const static Node NODE_1314732695264[] PROGMEM;
	const static Node NODE_1314732695424[] PROGMEM;
	const static Node NODE_1314732696624[] PROGMEM;
	const static Node NODE_1314732696704[] PROGMEM;
	const static Node NODE_1314732696864[] PROGMEM;
	const static Node NODE_1314732697584[] PROGMEM;
	const static Node NODE_1314733168880[] PROGMEM;
	const static Node NODE_1314734304016[] PROGMEM;
	const static Node NODE_1314732697664[] PROGMEM;
	const static Node NODE_1314732698704[] PROGMEM;
	const static Node NODE_1314732699024[] PROGMEM;
	const static Node NODE_1314732699344[] PROGMEM;
	const static Node NODE_1314732699584[] PROGMEM;
	const static Node NODE_1314732699984[] PROGMEM;
	const static Node NODE_1314732700224[] PROGMEM;
	const static Node NODE_1314732810512[] PROGMEM;
	const static Node NODE_1314732701104[] PROGMEM;
	const static Node NODE_1314732701344[] PROGMEM;
	const static Node NODE_1314732702464[] PROGMEM;
	const static Node NODE_1314732702384[] PROGMEM;
	const static Node NODE_1314732702704[] PROGMEM;
	const static Node NODE_1314732703024[] PROGMEM;
	const static Node NODE_1314732703184[] PROGMEM;
	const static Node NODE_1314732703104[] PROGMEM;
	const static Node NODE_1314732703344[] PROGMEM;
	const static Node NODE_1314732703504[] PROGMEM;
	const static Node NODE_1314733082080[] PROGMEM;
	const static Node NODE_1314732703664[] PROGMEM;
	const static Node NODE_1314732802432[] PROGMEM;
	const static Node NODE_1314732802672[] PROGMEM;
	const static Node NODE_1314732802592[] PROGMEM;
	const static Node NODE_1314732802832[] PROGMEM;
	const static Node NODE_1314732803872[] PROGMEM;
	const static Node NODE_1314732804032[] PROGMEM;
	const static Node NODE_1314732805312[] PROGMEM;
	const static Node NODE_1314732805392[] PROGMEM;
	const static Node NODE_1314732805712[] PROGMEM;
	const static Node NODE_1314732806592[] PROGMEM;
	const static Node NODE_1314732806832[] PROGMEM;
	const static Node NODE_1314732806992[] PROGMEM;
	const static Node NODE_1314732806912[] PROGMEM;
	const static Node NODE_1314732807152[] PROGMEM;
	const static Node NODE_1314732808272[] PROGMEM;
	const static Node NODE_1314734365152[] PROGMEM;
	const static Node NODE_1314732808592[] PROGMEM;
	const static Node NODE_1314732808672[] PROGMEM;
	const static Node NODE_1314733080880[] PROGMEM;
	const static Node NODE_1314733081040[] PROGMEM;
	const static Node NODE_1314732808432[] PROGMEM;
	const static Node NODE_1314732808832[] PROGMEM;
	const static Node NODE_1314732808992[] PROGMEM;
	const static Node NODE_1314732809312[] PROGMEM;
	const static Node NODE_1314732809392[] PROGMEM;
	const static Node NODE_1314732809792[] PROGMEM;
	const static Node NODE_1314732809872[] PROGMEM;
	const static Node NODE_1314732810272[] PROGMEM;
	const static Node NODE_1314734304176[] PROGMEM;
	const static Node NODE_1314734304416[] PROGMEM;
	const static Node NODE_1314734451792[] PROGMEM;
	const static Node NODE_1314732810832[] PROGMEM;
	const static Node NODE_1314732810992[] PROGMEM;
	const static Node NODE_1314732811152[] PROGMEM;
	const static Node NODE_1314733022464[] PROGMEM;
	const static Node NODE_1314733165760[] PROGMEM;
	const static Node NODE_1314733023344[] PROGMEM;
	const static Node NODE_1314733023664[] PROGMEM;
	const static Node NODE_1314733024144[] PROGMEM;
	const static Node NODE_1314733024544[] PROGMEM;
	const static Node NODE_1314733168480[] PROGMEM;
	const static Node NODE_1314734362912[] PROGMEM;
	const static Node NODE_1314733024624[] PROGMEM;
	const static Node NODE_1314734452272[] PROGMEM;
	const static Node NODE_1314734452352[] PROGMEM;
	const static Node NODE_1314734452192[] PROGMEM;
	const static Node NODE_1314733025264[] PROGMEM;
	const static Node NODE_1314733026224[] PROGMEM;
	const static Node NODE_1314734448672[] PROGMEM;
	const static Node NODE_1314733027104[] PROGMEM;
	const static Node NODE_1314734362512[] PROGMEM;
	const static Node NODE_1314734364512[] PROGMEM;
	const static Node NODE_1314734368992[] PROGMEM;
	const static Node NODE_1314734370192[] PROGMEM;
	const static Node NODE_1314734370272[] PROGMEM;
	const static Node NODE_1314733027904[] PROGMEM;
	const static Node NODE_1314733028144[] PROGMEM;
	const static Node NODE_1314733028864[] PROGMEM;
	const static Node NODE_1314733029184[] PROGMEM;
	const static Node NODE_1314733029504[] PROGMEM;
	const static Node NODE_1314733030704[] PROGMEM;
	const static Node NODE_1314733030944[] PROGMEM;
	const static Node NODE_1314733081520[] PROGMEM;
	const static Node NODE_1314733081600[] PROGMEM;
	const static Node NODE_1314733082320[] PROGMEM;
	const static Node NODE_1314734309136[] PROGMEM;
	const static Node NODE_1314733082640[] PROGMEM;
	const static Node NODE_1314733082560[] PROGMEM;
	const static Node NODE_1314734367392[] PROGMEM;
	const static Node NODE_1314734367952[] PROGMEM;
	const static Node NODE_1314734442032[] PROGMEM;
	const static Node NODE_1314733091520[] PROGMEM;
	const static Node NODE_1314733092240[] PROGMEM;
	const static Node NODE_1314733092080[] PROGMEM;
	const static Node NODE_1314734368032[] PROGMEM;
	const static Node NODE_1314733093040[] PROGMEM;
	const static Node NODE_1314733093200[] PROGMEM;
	const static Node NODE_1314733093680[] PROGMEM;
	const static Node NODE_1314733093840[] PROGMEM;
	const static Node NODE_1314733163920[] PROGMEM;
	const static Node NODE_1314733165040[] PROGMEM;
	const static Node NODE_1314733165120[] PROGMEM;
	const static Node NODE_1314733165280[] PROGMEM;
	const static Node NODE_1314733165920[] PROGMEM;
	const static Node NODE_1314733166080[] PROGMEM;
	const static Node NODE_1314733166240[] PROGMEM;
	const static Node NODE_1314733166400[] PROGMEM;
	const static Node NODE_1314733167840[] PROGMEM;
	const static Node NODE_1314733168400[] PROGMEM;
	const static Node NODE_1314733168560[] PROGMEM;
	const static Node NODE_1314733169200[] PROGMEM;
	const static Node NODE_1314733172960[] PROGMEM;
	const static Node NODE_1314733173040[] PROGMEM;
	const static Node NODE_1314733173520[] PROGMEM;
	const static Node NODE_1314733173200[] PROGMEM;
	const static Node NODE_1314733173680[] PROGMEM;
	const static Node NODE_1314734296416[] PROGMEM;
	const static Node NODE_1314734298016[] PROGMEM;
	const static Node NODE_1314734298336[] PROGMEM;
	const static Node NODE_1314734369792[] PROGMEM;
	const static Node NODE_1314734298736[] PROGMEM;
	const static Node NODE_1314734299216[] PROGMEM;
	const static Node NODE_1314734300896[] PROGMEM;
	const static Node NODE_1314734365472[] PROGMEM;
	const static Node NODE_1314734301456[] PROGMEM;
	const static Node NODE_1314734364832[] PROGMEM;
	const static Node NODE_1314734302976[] PROGMEM;
	const static Node NODE_1314734305136[] PROGMEM;
	const static Node NODE_1314734363952[] PROGMEM;
	const static Node NODE_1314734306016[] PROGMEM;
	const static Node NODE_1314734306256[] PROGMEM;
	const static Node NODE_1314734306496[] PROGMEM;
	const static Node NODE_1314734306656[] PROGMEM;
	const static Node NODE_1314734306576[] PROGMEM;
	const static Node NODE_1314734306896[] PROGMEM;
	const static Node NODE_1314734307216[] PROGMEM;
	const static Node NODE_1314734365712[] PROGMEM;
	const static Node NODE_1314734308656[] PROGMEM;
	const static Node NODE_1314734309296[] PROGMEM;
	const static Node NODE_1314734367312[] PROGMEM;
	const static Node NODE_1314734368352[] PROGMEM;
	const static Node NODE_1314734368592[] PROGMEM;
	const static Node NODE_1314734368672[] PROGMEM;
	const static Node NODE_1314734373152[] PROGMEM;
	const static Node NODE_1314734373312[] PROGMEM;
	const static Node NODE_1314734450592[] PROGMEM;
	const static Node NODE_1314734450992[] PROGMEM;
	const static Node NODE_1314734451312[] PROGMEM;

	const static LayeredKey aliases[][2];
	
	LayeredKey getAlias(uint8_t layer, uint8_t key);

	public:
	Compose() : currentNode(const_cast<Node*>(root)){
		//if this assertion fails, the struct in Node has to be reworked for the target architecture
		assert(sizeof(uint16_t) >= sizeof(Node*));
	}
	
	uint16_t transition(uint8_t layer, uint8_t key);
	void reset();
	
	


}; //Compose

#endif //__COMPOSE_H__