/***********************************************************************/
/******************* This file is generated by *************************/
/******************* the Compose Generator *****************************/
/***********************************************************************/

#include "Compose.gen.h"

//generated compose tree
const Node Compose::root[] PROGMEM = {
	{{0, 0, L1, KEY_TILDE}, {(uint16_t) NODE_1314732443264}},
	{{0, 0, L2, KEY_TILDE}, {(uint16_t) NODE_1314732442384}},
	{{0, 0, L6, KEY_NON_US_NUM}, {(uint16_t) NODE_1314732442704}},
	{{0, 0, L1, KEY_NON_US_NUM}, {(uint16_t) NODE_1314732442864}},
	{{0, 0, L1, KEY_EQUAL}, {(uint16_t) NODE_1314732443424}},
	{{0, 0, L2, KEY_EQUAL}, {(uint16_t) NODE_1314732443504}},
	{{0, 0, L3, KEY_TILDE}, {(uint16_t) NODE_1314732443744}},
	{{0, 0, L4, KEY_TILDE}, {(uint16_t) NODE_1314732443824}},
	{{0, 0, L3, KEY_EQUAL}, {(uint16_t) NODE_1314732444144}},
	{{0, 0, L2, KEY_NON_US_NUM}, {(uint16_t) NODE_1314732444304}},
	{{0, 0, L6, KEY_EQUAL}, {(uint16_t) NODE_1314732444624}},
	{{0, 0, L4, KEY_EQUAL}, {(uint16_t) NODE_1314732445264}},
	{{0, 0, L3, KEY_NON_US_NUM}, {(uint16_t) NODE_1314732445584}},
	{{0, 0, L4, KEY_NON_US_NUM}, {(uint16_t) NODE_1314732446144}},
	{{0, 0, L5, KEY_NON_US_NUM}, {(uint16_t) NODE_1314732445904}},
	{{0, 0, L5, KEY_EQUAL}, {(uint16_t) NODE_1314732445744}},
	{{0, 0, L5, KEY_TILDE}, {(uint16_t) NODE_1314732446544}},
	{{0, 0, L6, KEY_TILDE}, {(uint16_t) NODE_1314732641952}},
	{{1, 0, L3, KEY_TAB}, {(uint16_t) NODE_1314732641552}},
};

const Node Compose::NODE_1314732443264[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2c6}},
	{{0, 1, L1, KEY_TILDE}, {0x302}},
	{{0, 1, L1, KEY_SPACE}, {0x5e}},
	{{0, 1, L2, KEY_R}, {0xc2}},
	{{0, 1, L2, KEY_F}, {0xca}},
	{{0, 1, L2, KEY_D}, {0xce}},
	{{0, 1, L2, KEY_G}, {0xd4}},
	{{0, 1, L2, KEY_E}, {0xdb}},
	{{0, 1, L1, KEY_R}, {0xe2}},
	{{0, 1, L1, KEY_F}, {0xea}},
	{{0, 1, L1, KEY_D}, {0xee}},
	{{0, 1, L1, KEY_G}, {0xf4}},
	{{0, 1, L1, KEY_E}, {0xfb}},
	{{0, 1, L2, KEY_A}, {0x108}},
	{{0, 1, L1, KEY_A}, {0x109}},
	{{0, 1, L2, KEY_O}, {0x11c}},
	{{0, 1, L1, KEY_O}, {0x11d}},
	{{0, 1, L2, KEY_SEMICOLON}, {0x124}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x125}},
	{{0, 1, L2, KEY_Q}, {0x134}},
	{{0, 1, L1, KEY_Q}, {0x135}},
	{{0, 1, L2, KEY_L}, {0x15c}},
	{{0, 1, L1, KEY_L}, {0x15d}},
	{{0, 1, L2, KEY_Y}, {0x174}},
	{{0, 1, L1, KEY_Y}, {0x175}},
	{{0, 1, L2, KEY_P}, {0x176}},
	{{0, 1, L1, KEY_P}, {0x177}},
	{{0, 1, L2, KEY_LEFT_BRACE}, {0x1e90}},
	{{0, 1, L1, KEY_LEFT_BRACE}, {0x1e91}},
	{{0, 0, L6, KEY_TILDE}, {(uint16_t) NODE_1314732958528}},
	{{0, 1, L1, KEY_0}, {0x2070}},
	{{0, 0, L3, KEY_TAB}, {(uint16_t) NODE_1314733082880}},
	{{0, 1, L1, KEY_2}, {0xb2}},
	{{0, 1, L1, KEY_3}, {0xb3}},
	{{0, 1, L1, KEY_1}, {0xb9}},
	{{0, 1, L1, KEY_4}, {0x2074}},
	{{0, 1, L1, KEY_5}, {0x2075}},
	{{0, 1, L1, KEY_6}, {0x2076}},
	{{0, 1, L1, KEY_7}, {0x2077}},
	{{0, 1, L1, KEY_8}, {0x2078}},
	{{0, 1, L1, KEY_9}, {0x2079}},
	{{0, 1, L3, KEY_N}, {0x207a}},
	{{0, 1, L1, KEY_MINUS}, {0x207b}},
	{{0, 1, L3, KEY_O}, {0x207c}},
	{{0, 1, L3, KEY_J}, {0x207d}},
	{{0, 1, L3, KEY_K}, {0x207e}},
	{{0, 0, L3, KEY_TILDE}, {(uint16_t) NODE_1314733170480}},
	{{0, 1, L3, KEY_G}, {0x33d}},
	{{0, 0, L5, KEY_TILDE}, {(uint16_t) NODE_1314733173840}},
	{{0, 0, L3, KEY_NON_US_NUM}, {(uint16_t) NODE_1314733174560}},
	{{0, 1, L3, KEY_H}, {0x2c0}},
	{{0, 0, L3, KEY_EQUAL}, {(uint16_t) NODE_1314733177040}},
	{{0, 1, L5, KEY_P}, {0x1db7}},
	{{0, 1, L5, KEY_F}, {0x1d4b}},
	{{0, 1, L5, KEY_R}, {0x1d45}},
	{{0, 1, L5, KEY_NUM_LOCK}, {0x2a6f}},
	{{0, 1, L3, KEYPAD_4}, {0x219e}},
	{{0, 1, L3, KEYPAD_8}, {0x219f}},
	{{0, 1, L3, KEYPAD_6}, {0x21a0}},
	{{0, 1, L3, KEYPAD_2}, {0x21a1}},
	{{0, 1, L3, KEY_I}, {0x20d7}},
	{{0, 1, L3, KEY_U}, {0x20d6}},
	{{1, 1, L3, KEY_Q}, {0x22ef}},
};

const Node Compose::NODE_1314732958528[] PROGMEM = {
	{{0, 1, L2, KEY_R}, {0x1eac}},
	{{0, 1, L1, KEY_R}, {0x1ead}},
	{{0, 1, L2, KEY_F}, {0x1ec6}},
	{{0, 1, L1, KEY_F}, {0x1ec7}},
	{{0, 1, L2, KEY_G}, {0x1ed8}},
	{{1, 1, L1, KEY_G}, {0x1ed9}},
};

const Node Compose::NODE_1314733082880[] PROGMEM = {
	{{0, 0, L3, KEY_W}, {(uint16_t) NODE_1314733083040}},
	{{0, 0, L2, KEY_L}, {(uint16_t) NODE_1314733086960}},
	{{0, 0, L1, KEY_L}, {(uint16_t) NODE_1314733087120}},
	{{0, 0, L2, KEY_K}, {(uint16_t) NODE_1314733087680}},
	{{0, 0, L1, KEY_K}, {(uint16_t) NODE_1314733087840}},
	{{0, 0, L3, KEY_C}, {(uint16_t) NODE_1314733170400}},
	{{0, 0, L1, KEY_Z}, {(uint16_t) NODE_1314733170560}},
	{{0, 0, L1, KEY_J}, {(uint16_t) NODE_1314733173600}},
	{{0, 0, L1, KEY_Q}, {(uint16_t) NODE_1314733174000}},
	{{0, 0, L2, KEY_J}, {(uint16_t) NODE_1314733174480}},
	{{0, 0, L1, KEY_O}, {(uint16_t) NODE_1314733174800}},
	{{0, 0, L1, KEY_I}, {(uint16_t) NODE_1314733175040}},
	{{0, 0, L1, KEY_LEFT_BRACE}, {(uint16_t) NODE_1314733175200}},
	{{0, 0, L1, KEY_W}, {(uint16_t) NODE_1314733176480}},
	{{0, 0, L2, KEY_W}, {(uint16_t) NODE_1314733176640}},
	{{0, 0, L1, KEY_MINUS}, {(uint16_t) NODE_1314733177280}},
	{{0, 0, L2, KEY_D}, {(uint16_t) NODE_1314733177840}},
	{{0, 0, L1, KEY_F}, {(uint16_t) NODE_1314733178240}},
	{{1, 0, L1, KEY_3}, {(uint16_t) NODE_1314733178320}},
};

const Node Compose::NODE_1314733083040[] PROGMEM = {
	{{0, 1, L1, KEY_D}, {0x2071}},
	{{1, 1, L1, KEY_J}, {0x207f}},
};

const Node Compose::NODE_1314733086960[] PROGMEM = {
	{{0, 1, L2, KEY_H}, {0x2120}},
	{{1, 1, L1, KEY_H}, {0x2120}},
};

const Node Compose::NODE_1314733087120[] PROGMEM = {
	{{0, 1, L2, KEY_H}, {0x2120}},
	{{0, 1, L1, KEY_H}, {0x2120}},
	{{1, 1, L1, KEY_SEMICOLON}, {0x1db4}},
};

const Node Compose::NODE_1314733087680[] PROGMEM = {
	{{0, 1, L2, KEY_H}, {0x2122}},
	{{1, 1, L1, KEY_H}, {0x2122}},
};

const Node Compose::NODE_1314733087840[] PROGMEM = {
	{{0, 1, L2, KEY_H}, {0x2122}},
	{{1, 1, L1, KEY_H}, {0x2122}},
};

const Node Compose::NODE_1314733170400[] PROGMEM = {
	{{1, 1, L3, KEY_T}, {0xa71b}},
};

const Node Compose::NODE_1314733170560[] PROGMEM = {
	{{0, 1, L3, KEY_C}, {0xa71c}},
	{{1, 1, L3, KEY_K}, {0x1db9}},
};

const Node Compose::NODE_1314733173600[] PROGMEM = {
	{{0, 1, L1, KEY_W}, {0x1daf}},
	{{1, 1, L1, KEY_O}, {0x1d51}},
};

const Node Compose::NODE_1314733174000[] PROGMEM = {
	{{1, 1, L1, KEY_J}, {0x1dae}},
};

const Node Compose::NODE_1314733174480[] PROGMEM = {
	{{1, 1, L2, KEY_J}, {0x1db0}},
};

const Node Compose::NODE_1314733174800[] PROGMEM = {
	{{1, 1, L1, KEY_O}, {0x1da2}},
};

const Node Compose::NODE_1314733175040[] PROGMEM = {
	{{1, 1, L1, KEY_SEMICOLON}, {0x1d9e}},
};

const Node Compose::NODE_1314733175200[] PROGMEM = {
	{{0, 1, L1, KEY_SEMICOLON}, {0x1dbe}},
	{{1, 1, L1, KEY_LEFT_BRACE}, {0x1dbe}},
};

const Node Compose::NODE_1314733176480[] PROGMEM = {
	{{1, 1, L1, KEY_W}, {0x1da9}},
};

const Node Compose::NODE_1314733176640[] PROGMEM = {
	{{1, 1, L2, KEY_W}, {0x1dab}},
};

const Node Compose::NODE_1314733177280[] PROGMEM = {
	{{0, 1, L1, KEY_D}, {0x1da4}},
	{{0, 1, L1, KEY_E}, {0x1db6}},
	{{0, 1, L1, KEY_G}, {0x1db1}},
	{{1, 1, L2, KEY_D}, {0x1da7}},
};

const Node Compose::NODE_1314733177840[] PROGMEM = {
	{{1, 1, L2, KEY_D}, {0x1da6}},
};

const Node Compose::NODE_1314733178240[] PROGMEM = {
	{{1, 1, L1, KEY_F}, {0x1d4a}},
};

const Node Compose::NODE_1314733178320[] PROGMEM = {
	{{1, 1, L1, KEY_3}, {0x1d9f}},
};

const Node Compose::NODE_1314733170480[] PROGMEM = {
	{{0, 1, L2, KEY_W}, {0x31a}},
	{{0, 1, L2, KEY_S}, {0x2b6}},
	{{0, 1, L3, KEY_H}, {0x2c1}},
	{{0, 1, L1, KEY_S}, {0x2b4}},
	{{0, 0, L3, KEY_TAB}, {(uint16_t) NODE_1314733176320}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x1da3}},
	{{0, 1, L1, KEY_H}, {0x1d5a}},
	{{0, 1, L1, KEY_Z}, {0x1dba}},
	{{0, 1, L1, KEY_A}, {0x1d53}},
	{{0, 1, L1, KEY_R}, {0x1d44}},
	{{0, 1, L5, KEY_R}, {0x1d9b}},
	{{1, 1, L3, KEYPAD_6}, {0x219e}},
};

const Node Compose::NODE_1314733176320[] PROGMEM = {
	{{1, 0, L1, KEY_SEMICOLON}, {(uint16_t) NODE_1314733176720}},
};

const Node Compose::NODE_1314733176720[] PROGMEM = {
	{{1, 1, L1, KEY_J}, {0x1dad}},
};

const Node Compose::NODE_1314733173840[] PROGMEM = {
	{{0, 1, L1, KEY_H}, {0x1dac}},
	{{0, 1, L1, KEY_J}, {0x1d51}},
	{{0, 1, L1, KEY_L}, {0x1db3}},
	{{0, 1, L1, KEY_LEFT_BRACE}, {0x1dbc}},
	{{0, 1, L1, KEY_Q}, {0x1da8}},
	{{0, 1, L1, KEY_X}, {0x2e0}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x2b1}},
	{{1, 0, L3, KEY_TILDE}, {(uint16_t) NODE_1314733176400}},
};

const Node Compose::NODE_1314733176400[] PROGMEM = {
	{{1, 1, L1, KEY_S}, {0x2b5}},
};

const Node Compose::NODE_1314733174560[] PROGMEM = {
	{{0, 1, L1, KEY_Q}, {0x1da1}},
	{{0, 1, L2, KEY_Q}, {0x1da1}},
	{{0, 1, L1, KEY_D}, {0x1da4}},
	{{0, 1, L1, KEY_E}, {0x1db6}},
	{{0, 1, L2, KEY_D}, {0x1da7}},
	{{1, 0, L3, KEY_TAB}, {(uint16_t) NODE_1314734293216}},
};

const Node Compose::NODE_1314734293216[] PROGMEM = {
	{{1, 0, L2, KEY_D}, {(uint16_t) NODE_1314734293536}},
};

const Node Compose::NODE_1314734293536[] PROGMEM = {
	{{1, 1, L2, KEY_D}, {0x1da7}},
};

const Node Compose::NODE_1314733177040[] PROGMEM = {
	{{0, 1, L1, KEY_A}, {0x1d9d}},
	{{1, 1, L1, KEY_LEFT_BRACE}, {0x1dbd}},
};

const Node Compose::NODE_1314732442384[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2c7}},
	{{0, 1, L2, KEY_TILDE}, {0x30c}},
	{{0, 0, L3, KEY_TAB}, {(uint16_t) NODE_1314732700304}},
	{{0, 1, L1, KEY_0}, {0x2080}},
	{{0, 1, L1, KEY_1}, {0x2081}},
	{{0, 1, L1, KEY_2}, {0x2082}},
	{{0, 1, L1, KEY_3}, {0x2083}},
	{{0, 1, L1, KEY_4}, {0x2084}},
	{{0, 1, L1, KEY_5}, {0x2085}},
	{{0, 1, L1, KEY_6}, {0x2086}},
	{{0, 1, L1, KEY_7}, {0x2087}},
	{{0, 1, L1, KEY_8}, {0x2088}},
	{{0, 1, L1, KEY_9}, {0x2089}},
	{{0, 1, L1, KEY_SPACE}, {0x2c7}},
	{{0, 1, L2, KEY_A}, {0x10c}},
	{{0, 1, L1, KEY_A}, {0x10d}},
	{{0, 1, L2, KEY_I}, {0x10e}},
	{{0, 1, L1, KEY_I}, {0x10f}},
	{{0, 1, L2, KEY_F}, {0x11a}},
	{{0, 1, L1, KEY_F}, {0x11b}},
	{{0, 1, L2, KEY_W}, {0x13d}},
	{{0, 1, L1, KEY_W}, {0x13e}},
	{{0, 1, L2, KEY_J}, {0x147}},
	{{0, 1, L1, KEY_J}, {0x148}},
	{{0, 1, L2, KEY_S}, {0x158}},
	{{0, 1, L1, KEY_S}, {0x159}},
	{{0, 1, L2, KEY_L}, {0x160}},
	{{0, 1, L1, KEY_L}, {0x161}},
	{{0, 1, L2, KEY_K}, {0x164}},
	{{0, 1, L1, KEY_K}, {0x165}},
	{{0, 1, L2, KEY_LEFT_BRACE}, {0x17d}},
	{{0, 1, L1, KEY_LEFT_BRACE}, {0x17e}},
	{{0, 1, L2, KEY_R}, {0x1cd}},
	{{0, 1, L1, KEY_R}, {0x1ce}},
	{{0, 1, L2, KEY_D}, {0x1cf}},
	{{0, 1, L1, KEY_D}, {0x1d0}},
	{{0, 1, L2, KEY_G}, {0x1d1}},
	{{0, 1, L1, KEY_G}, {0x1d2}},
	{{0, 1, L2, KEY_E}, {0x1d3}},
	{{0, 1, L1, KEY_E}, {0x1d4}},
	{{0, 1, L2, KEY_C}, {0x1d9}},
	{{0, 0, L4, KEY_EQUAL}, {(uint16_t) NODE_1314732878048}},
	{{0, 1, L1, KEY_C}, {0x1da}},
	{{0, 1, L2, KEY_O}, {0x1e6}},
	{{0, 1, L1, KEY_O}, {0x1e7}},
	{{0, 1, L2, KEY_SLASH}, {0x1e8}},
	{{0, 1, L1, KEY_SLASH}, {0x1e9}},
	{{0, 1, L1, KEY_Q}, {0x1f0}},
	{{0, 1, L2, KEY_SEMICOLON}, {0x21e}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x21f}},
	{{0, 1, L3, KEY_O}, {0x225a}},
	{{0, 1, L3, KEYPAD_6}, {0x21a3}},
	{{1, 1, L3, KEYPAD_4}, {0x21a2}},
};

const Node Compose::NODE_1314732700304[] PROGMEM = {
	{{0, 0, L2, KEY_I}, {(uint16_t) NODE_1314732700544}},
	{{0, 0, L1, KEY_I}, {(uint16_t) NODE_1314732700704}},
	{{0, 0, L2, KEY_LEFT_BRACE}, {(uint16_t) NODE_1314733164160}},
	{{1, 0, L1, KEY_LEFT_BRACE}, {(uint16_t) NODE_1314733164320}},
};

const Node Compose::NODE_1314732700544[] PROGMEM = {
	{{0, 1, L2, KEY_LEFT_BRACE}, {0x1c4}},
	{{1, 1, L1, KEY_LEFT_BRACE}, {0x1c5}},
};

const Node Compose::NODE_1314732700704[] PROGMEM = {
	{{1, 1, L1, KEY_LEFT_BRACE}, {0x1c6}},
};

const Node Compose::NODE_1314733164160[] PROGMEM = {
	{{1, 1, L2, KEY_SEMICOLON}, {0x1ee}},
};

const Node Compose::NODE_1314733164320[] PROGMEM = {
	{{1, 1, L1, KEY_SEMICOLON}, {0x1ef}},
};

const Node Compose::NODE_1314732878048[] PROGMEM = {
	{{0, 1, L2, KEY_E}, {0x1d9}},
	{{1, 1, L1, KEY_E}, {0x1da}},
};

const Node Compose::NODE_1314732442704[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2d8}},
	{{0, 1, L6, KEY_NON_US_NUM}, {0x306}},
	{{0, 1, L2, KEY_SEMICOLON}, {0x1e2a}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x1e2b}},
	{{0, 1, L5, KEY_5}, {0x263f}},
	{{0, 1, L1, KEY_SPACE}, {0x2d8}},
	{{0, 1, L2, KEY_R}, {0x102}},
	{{0, 1, L1, KEY_R}, {0x103}},
	{{0, 1, L2, KEY_F}, {0x114}},
	{{0, 1, L1, KEY_F}, {0x115}},
	{{0, 1, L2, KEY_O}, {0x11e}},
	{{0, 1, L1, KEY_O}, {0x11f}},
	{{0, 1, L2, KEY_D}, {0x12c}},
	{{0, 1, L1, KEY_D}, {0x12d}},
	{{0, 1, L2, KEY_G}, {0x14e}},
	{{0, 1, L1, KEY_G}, {0x14f}},
	{{0, 1, L2, KEY_E}, {0x16c}},
	{{0, 1, L1, KEY_E}, {0x16d}},
	{{0, 0, L2, KEY_EQUAL}, {(uint16_t) NODE_1314732883488}},
	{{0, 0, L6, KEY_TILDE}, {(uint16_t) NODE_1314732959808}},
	{{0, 1, L5, KEY_R}, {0x1fb0}},
	{{0, 1, L5, KEY_D}, {0x1fd0}},
	{{1, 1, L5, KEY_P}, {0x1fe0}},
};

const Node Compose::NODE_1314732883488[] PROGMEM = {
	{{0, 1, L2, KEY_F}, {0x1e1c}},
	{{1, 1, L1, KEY_F}, {0x1e1d}},
};

const Node Compose::NODE_1314732959808[] PROGMEM = {
	{{0, 1, L2, KEY_R}, {0x1eb6}},
	{{1, 1, L1, KEY_R}, {0x1eb7}},
};

const Node Compose::NODE_1314732442864[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0xb4}},
	{{0, 1, L1, KEY_NON_US_NUM}, {0x301}},
	{{0, 0, L3, KEY_NON_US_NUM}, {(uint16_t) NODE_1314732693904}},
	{{0, 0, L3, KEY_TAB}, {(uint16_t) NODE_1314732698304}},
	{{0, 1, L1, KEY_SPACE}, {0xb4}},
	{{0, 1, L2, KEY_R}, {0xc1}},
	{{0, 1, L2, KEY_F}, {0xc9}},
	{{0, 1, L2, KEY_D}, {0xcd}},
	{{0, 1, L2, KEY_G}, {0xd3}},
	{{0, 1, L2, KEY_E}, {0xda}},
	{{0, 1, L2, KEY_P}, {0xdd}},
	{{0, 1, L1, KEY_R}, {0xe1}},
	{{0, 1, L1, KEY_F}, {0xe9}},
	{{0, 1, L1, KEY_D}, {0xed}},
	{{0, 1, L1, KEY_G}, {0xf3}},
	{{0, 1, L1, KEY_E}, {0xfa}},
	{{0, 1, L1, KEY_P}, {0xfd}},
	{{0, 1, L2, KEY_A}, {0x106}},
	{{0, 1, L1, KEY_A}, {0x107}},
	{{0, 1, L2, KEY_W}, {0x139}},
	{{0, 1, L1, KEY_W}, {0x13a}},
	{{0, 1, L2, KEY_J}, {0x143}},
	{{0, 1, L1, KEY_J}, {0x144}},
	{{0, 1, L2, KEY_S}, {0x154}},
	{{0, 1, L1, KEY_S}, {0x155}},
	{{0, 1, L2, KEY_L}, {0x15a}},
	{{0, 1, L1, KEY_L}, {0x15b}},
	{{0, 1, L2, KEY_LEFT_BRACE}, {0x179}},
	{{0, 1, L1, KEY_LEFT_BRACE}, {0x17a}},
	{{0, 1, L2, KEY_C}, {0x1d7}},
	{{0, 0, L4, KEY_EQUAL}, {(uint16_t) NODE_1314732877728}},
	{{0, 1, L1, KEY_C}, {0x1d8}},
	{{0, 1, L2, KEY_O}, {0x1f4}},
	{{0, 1, L1, KEY_O}, {0x1f5}},
	{{0, 0, L3, KEY_EQUAL}, {(uint16_t) NODE_1314732880208}},
	{{0, 0, L2, KEY_EQUAL}, {(uint16_t) NODE_1314732882288}},
	{{0, 0, L6, KEY_EQUAL}, {(uint16_t) NODE_1314732883248}},
	{{0, 1, L2, KEY_SLASH}, {0x1e30}},
	{{0, 1, L1, KEY_SLASH}, {0x1e31}},
	{{0, 1, L2, KEY_H}, {0x1e3e}},
	{{0, 1, L1, KEY_H}, {0x1e3f}},
	{{0, 0, L2, KEY_NON_US_NUM}, {(uint16_t) NODE_1314732951968}},
	{{0, 1, L2, KEY_N}, {0x1e54}},
	{{0, 1, L1, KEY_N}, {0x1e55}},
	{{0, 1, L2, KEY_Y}, {0x1e82}},
	{{0, 1, L1, KEY_Y}, {0x1e83}},
	{{0, 0, L1, KEY_TILDE}, {(uint16_t) NODE_1314732957648}},
	{{0, 0, L6, KEY_NON_US_NUM}, {(uint16_t) NODE_1314732958768}},
	{{0, 0, L5, KEY_TILDE}, {(uint16_t) NODE_1314732962768}},
	{{0, 0, L5, KEY_NON_US_NUM}, {(uint16_t) NODE_1314733015344}},
	{{0, 0, L5, KEY_EQUAL}, {(uint16_t) NODE_1314733015504}},
	{{0, 1, L3, KEYPAD_4}, {0x21bc}},
	{{0, 1, L3, KEYPAD_8}, {0x21bf}},
	{{0, 1, L3, KEYPAD_6}, {0x21c1}},
	{{1, 1, L3, KEYPAD_2}, {0x21c2}},
};

const Node Compose::NODE_1314732693904[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1fe}},
	{{1, 1, L1, KEY_G}, {0x1ff}},
};

const Node Compose::NODE_1314732698304[] PROGMEM = {
	{{0, 0, L2, KEY_R}, {(uint16_t) NODE_1314732698544}},
	{{1, 0, L1, KEY_R}, {(uint16_t) NODE_1314732698464}},
};

const Node Compose::NODE_1314732698544[] PROGMEM = {
	{{1, 1, L2, KEY_F}, {0x1fc}},
};

const Node Compose::NODE_1314732698464[] PROGMEM = {
	{{1, 1, L1, KEY_F}, {0x1fd}},
};

const Node Compose::NODE_1314732877728[] PROGMEM = {
	{{0, 1, L2, KEY_E}, {0x1d7}},
	{{0, 1, L1, KEY_E}, {0x1d8}},
	{{0, 1, L2, KEY_D}, {0x1e2e}},
	{{1, 1, L1, KEY_D}, {0x1e2f}},
};

const Node Compose::NODE_1314732880208[] PROGMEM = {
	{{0, 1, L2, KEY_R}, {0x1fa}},
	{{1, 1, L1, KEY_R}, {0x1fb}},
};

const Node Compose::NODE_1314732882288[] PROGMEM = {
	{{0, 1, L2, KEY_A}, {0x1e08}},
	{{1, 1, L1, KEY_A}, {0x1e09}},
};

const Node Compose::NODE_1314732883248[] PROGMEM = {
	{{0, 1, L2, KEY_F}, {0x1e16}},
	{{0, 1, L1, KEY_F}, {0x1e17}},
	{{0, 1, L2, KEY_G}, {0x1e52}},
	{{1, 1, L1, KEY_G}, {0x1e53}},
};

const Node Compose::NODE_1314732951968[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1e4c}},
	{{0, 1, L1, KEY_G}, {0x1e4d}},
	{{0, 1, L2, KEY_E}, {0x1e78}},
	{{1, 1, L1, KEY_E}, {0x1e79}},
};

const Node Compose::NODE_1314732957648[] PROGMEM = {
	{{0, 1, L2, KEY_R}, {0x1ea4}},
	{{0, 1, L1, KEY_R}, {0x1ea5}},
	{{0, 1, L2, KEY_F}, {0x1ebe}},
	{{0, 1, L1, KEY_F}, {0x1ebf}},
	{{0, 1, L2, KEY_G}, {0x1ed0}},
	{{1, 1, L1, KEY_G}, {0x1ed1}},
};

const Node Compose::NODE_1314732958768[] PROGMEM = {
	{{0, 1, L2, KEY_R}, {0x1eae}},
	{{1, 1, L1, KEY_R}, {0x1eaf}},
};

const Node Compose::NODE_1314732962768[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1eda}},
	{{0, 1, L1, KEY_G}, {0x1edb}},
	{{0, 1, L2, KEY_E}, {0x1ee8}},
	{{1, 1, L1, KEY_E}, {0x1ee9}},
};

const Node Compose::NODE_1314733015344[] PROGMEM = {
	{{0, 1, L5, KEY_R}, {0x1f04}},
	{{0, 1, L5, KEY_F}, {0x1f14}},
	{{0, 1, L5, KEY_V}, {0x1f24}},
	{{0, 1, L5, KEY_D}, {0x1f34}},
	{{0, 1, L5, KEY_G}, {0x1f44}},
	{{0, 1, L5, KEY_P}, {0x1f54}},
	{{0, 1, L5, KEY_Y}, {0x1f64}},
	{{1, 1, L6, KEY_Y}, {0x1f6c}},
};

const Node Compose::NODE_1314733015504[] PROGMEM = {
	{{0, 1, L5, KEY_R}, {0x1f05}},
	{{0, 1, L5, KEY_F}, {0x1f15}},
	{{0, 1, L5, KEY_V}, {0x1f25}},
	{{0, 1, L5, KEY_D}, {0x1f35}},
	{{0, 1, L5, KEY_G}, {0x1f45}},
	{{0, 1, L5, KEY_P}, {0x1f55}},
	{{0, 1, L5, KEY_Y}, {0x1f65}},
	{{1, 1, L6, KEY_Y}, {0x1f6d}},
};

const Node Compose::NODE_1314732443424[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x60}},
	{{0, 1, L1, KEY_EQUAL}, {0x300}},
	{{0, 1, L1, KEY_SPACE}, {0x60}},
	{{0, 1, L2, KEY_R}, {0xc0}},
	{{0, 1, L2, KEY_F}, {0xc8}},
	{{0, 1, L2, KEY_D}, {0xcc}},
	{{0, 1, L2, KEY_G}, {0xd2}},
	{{0, 1, L2, KEY_E}, {0xd9}},
	{{0, 1, L1, KEY_R}, {0xe0}},
	{{0, 1, L1, KEY_F}, {0xe8}},
	{{0, 1, L1, KEY_D}, {0xec}},
	{{0, 1, L1, KEY_G}, {0xf2}},
	{{0, 1, L1, KEY_E}, {0xf9}},
	{{0, 1, L2, KEY_C}, {0x1db}},
	{{0, 0, L4, KEY_EQUAL}, {(uint16_t) NODE_1314732878528}},
	{{0, 1, L1, KEY_C}, {0x1dc}},
	{{0, 1, L2, KEY_J}, {0x1f8}},
	{{0, 1, L1, KEY_J}, {0x1f9}},
	{{0, 0, L6, KEY_EQUAL}, {(uint16_t) NODE_1314732883008}},
	{{0, 1, L2, KEY_Y}, {0x1e80}},
	{{0, 1, L1, KEY_Y}, {0x1e81}},
	{{0, 0, L1, KEY_TILDE}, {(uint16_t) NODE_1314732957728}},
	{{0, 0, L6, KEY_NON_US_NUM}, {(uint16_t) NODE_1314732959088}},
	{{0, 0, L5, KEY_TILDE}, {(uint16_t) NODE_1314732963008}},
	{{0, 1, L2, KEY_P}, {0x1ef2}},
	{{0, 1, L1, KEY_P}, {0x1ef3}},
	{{0, 0, L5, KEY_NON_US_NUM}, {(uint16_t) NODE_1314733015104}},
	{{0, 0, L5, KEY_EQUAL}, {(uint16_t) NODE_1314733015184}},
	{{0, 1, L5, KEY_R}, {0x1f70}},
	{{0, 1, L5, KEY_F}, {0x1f72}},
	{{0, 1, L5, KEY_V}, {0x1f74}},
	{{0, 1, L5, KEY_D}, {0x1f76}},
	{{0, 1, L5, KEY_G}, {0x1f78}},
	{{0, 1, L5, KEY_P}, {0x1f7a}},
	{{0, 1, L5, KEY_Y}, {0x1f7c}},
	{{0, 1, L6, KEY_Y}, {0x1ffa}},
	{{0, 1, L3, KEYPAD_4}, {0x21bd}},
	{{0, 1, L3, KEYPAD_8}, {0x21be}},
	{{0, 1, L3, KEYPAD_6}, {0x21c0}},
	{{1, 1, L3, KEYPAD_2}, {0x21c3}},
};

const Node Compose::NODE_1314732878528[] PROGMEM = {
	{{0, 1, L2, KEY_E}, {0x1db}},
	{{0, 1, L1, KEY_E}, {0x1dc}},
	{{0, 1, L5, KEY_D}, {0x1fd2}},
	{{1, 1, L5, KEY_P}, {0x1fe2}},
};

const Node Compose::NODE_1314732883008[] PROGMEM = {
	{{0, 1, L2, KEY_F}, {0x1e14}},
	{{0, 1, L1, KEY_F}, {0x1e15}},
	{{0, 1, L2, KEY_G}, {0x1e50}},
	{{1, 1, L1, KEY_G}, {0x1e51}},
};

const Node Compose::NODE_1314732957728[] PROGMEM = {
	{{0, 1, L2, KEY_R}, {0x1ea6}},
	{{0, 1, L1, KEY_R}, {0x1ea7}},
	{{0, 1, L2, KEY_F}, {0x1ec0}},
	{{0, 1, L1, KEY_F}, {0x1ec1}},
	{{0, 1, L2, KEY_G}, {0x1ed2}},
	{{1, 1, L1, KEY_G}, {0x1ed3}},
};

const Node Compose::NODE_1314732959088[] PROGMEM = {
	{{0, 1, L2, KEY_R}, {0x1eb0}},
	{{1, 1, L1, KEY_R}, {0x1eb1}},
};

const Node Compose::NODE_1314732963008[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1edc}},
	{{0, 1, L1, KEY_G}, {0x1edd}},
	{{0, 1, L2, KEY_E}, {0x1eea}},
	{{1, 1, L1, KEY_E}, {0x1eeb}},
};

const Node Compose::NODE_1314733015104[] PROGMEM = {
	{{0, 1, L5, KEY_R}, {0x1f02}},
	{{0, 1, L5, KEY_F}, {0x1f12}},
	{{0, 1, L5, KEY_V}, {0x1f22}},
	{{0, 1, L5, KEY_D}, {0x1f32}},
	{{0, 1, L5, KEY_G}, {0x1f42}},
	{{0, 1, L5, KEY_P}, {0x1f52}},
	{{0, 1, L5, KEY_Y}, {0x1f62}},
	{{1, 1, L6, KEY_Y}, {0x1f6a}},
};

const Node Compose::NODE_1314733015184[] PROGMEM = {
	{{0, 1, L5, KEY_R}, {0x1f03}},
	{{0, 1, L5, KEY_F}, {0x1f13}},
	{{0, 1, L5, KEY_V}, {0x1f23}},
	{{0, 1, L5, KEY_D}, {0x1f33}},
	{{0, 1, L5, KEY_G}, {0x1f43}},
	{{0, 1, L5, KEY_P}, {0x1f53}},
	{{0, 1, L5, KEY_Y}, {0x1f63}},
	{{1, 1, L6, KEY_Y}, {0x1f6b}},
};

const Node Compose::NODE_1314732443504[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0xb8}},
	{{0, 1, L2, KEY_EQUAL}, {0x327}},
	{{0, 1, L2, KEY_R}, {0x104}},
	{{0, 1, L1, KEY_R}, {0x105}},
	{{0, 1, L2, KEY_F}, {0x118}},
	{{0, 1, L1, KEY_F}, {0x119}},
	{{0, 1, L2, KEY_D}, {0x12e}},
	{{0, 1, L1, KEY_D}, {0x12f}},
	{{0, 1, L2, KEY_E}, {0x172}},
	{{0, 1, L1, KEY_E}, {0x173}},
	{{0, 1, L2, KEY_G}, {0x1ea}},
	{{0, 1, L1, KEY_G}, {0x1eb}},
	{{0, 1, L1, KEY_SPACE}, {0xb8}},
	{{0, 1, L2, KEY_A}, {0xc7}},
	{{0, 1, L1, KEY_A}, {0xe7}},
	{{0, 1, L2, KEY_O}, {0x122}},
	{{0, 1, L1, KEY_O}, {0x123}},
	{{0, 1, L2, KEY_SLASH}, {0x136}},
	{{0, 1, L1, KEY_SLASH}, {0x137}},
	{{0, 1, L2, KEY_W}, {0x13b}},
	{{0, 1, L1, KEY_W}, {0x13c}},
	{{0, 1, L2, KEY_J}, {0x145}},
	{{0, 1, L1, KEY_J}, {0x146}},
	{{0, 1, L2, KEY_S}, {0x156}},
	{{0, 1, L1, KEY_S}, {0x157}},
	{{0, 1, L2, KEY_L}, {0x15e}},
	{{0, 1, L1, KEY_L}, {0x15f}},
	{{0, 1, L2, KEY_K}, {0x162}},
	{{0, 1, L1, KEY_K}, {0x163}},
	{{0, 1, L2, KEY_I}, {0x1e10}},
	{{0, 1, L1, KEY_I}, {0x1e11}},
	{{0, 1, L2, KEY_SEMICOLON}, {0x1e28}},
	{{1, 1, L1, KEY_SEMICOLON}, {0x1e29}},
};

const Node Compose::NODE_1314732443744[] PROGMEM = {
	{{0, 0, L2, KEY_EQUAL}, {(uint16_t) NODE_1314732443904}},
	{{0, 0, L4, KEY_NON_US_NUM}, {(uint16_t) NODE_1314732446304}},
	{{0, 1, L5, KEY_SPACE}, {0x21bb}},
	{{0, 0, L6, KEY_NON_US_NUM}, {(uint16_t) NODE_1314732640832}},
	{{0, 1, L1, KEY_SPACE}, {0x21bb}},
	{{0, 1, L3, KEY_SEMICOLON}, {0x2025}},
	{{0, 1, L3, KEY_Q}, {0x22ee}},
	{{0, 1, L5, KEY_5}, {0x2641}},
	{{0, 1, L3, KEY_R}, {0x2423}},
	{{0, 1, L3, KEYPAD_3}, {0x21cb}},
	{{0, 1, L1, KEY_R}, {0x250}},
	{{0, 1, L2, KEY_A}, {0x186}},
	{{0, 1, L1, KEY_A}, {0x254}},
	{{0, 1, L1, KEY_F}, {0x258}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x265}},
	{{0, 1, L1, KEY_H}, {0x26f}},
	{{0, 1, L2, KEY_S}, {0x281}},
	{{0, 1, L1, KEY_S}, {0x279}},
	{{0, 0, L3, KEY_TAB}, {(uint16_t) NODE_1314732812752}},
	{{0, 1, L2, KEY_L}, {0x1a7}},
	{{0, 1, L2, KEY_Z}, {0x245}},
	{{0, 1, L1, KEY_Z}, {0x28c}},
	{{0, 1, L1, KEY_Y}, {0x28d}},
	{{0, 1, L1, KEY_P}, {0x28e}},
	{{0, 1, L5, KEY_W}, {0x28e}},
	{{0, 1, L1, KEY_3}, {0x190}},
	{{0, 1, L5, KEY_R}, {0x252}},
	{{0, 1, L6, KEY_Y}, {0x1b1}},
	{{0, 1, L5, KEY_K}, {0x27e}},
	{{0, 1, L3, KEY_K}, {0x203f}},
	{{0, 1, L3, KEY_J}, {0x361}},
	{{0, 0, L3, KEY_EQUAL}, {(uint16_t) NODE_1314733171040}},
	{{0, 0, L4, KEY_EQUAL}, {(uint16_t) NODE_1314733171280}},
	{{0, 0, L2, KEY_NON_US_NUM}, {(uint16_t) NODE_1314733171520}},
	{{0, 1, L3, KEYPAD_ADD}, {0x2213}},
	{{0, 1, L6, KEY_N}, {0x2210}},
	{{0, 1, L6, KEY_G}, {0x220b}},
	{{0, 1, L6, KEY_A}, {0x2283}},
	{{0, 1, L3, KEY_V}, {0x2240}},
	{{0, 1, L3, KEY_P}, {0x214b}},
	{{0, 1, L3, KEY_Z}, {0x2a33}},
	{{0, 1, L3, KEYPAD_6}, {0x2190}},
	{{1, 0, L5, KEY_TILDE}, {(uint16_t) NODE_1314734371232}},
};

const Node Compose::NODE_1314732443904[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2db}},
	{{0, 1, L2, KEY_EQUAL}, {0x328}},
	{{0, 1, L1, KEY_SPACE}, {0x2db}},
	{{0, 1, L2, KEY_F}, {0x228}},
	{{1, 1, L1, KEY_F}, {0x229}},
};

const Node Compose::NODE_1314732446304[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2f5}},
	{{0, 1, L4, KEY_NON_US_NUM}, {0x30f}},
	{{0, 1, L2, KEY_R}, {0x200}},
	{{0, 1, L1, KEY_R}, {0x201}},
	{{0, 1, L2, KEY_F}, {0x204}},
	{{0, 1, L1, KEY_F}, {0x205}},
	{{0, 1, L2, KEY_D}, {0x208}},
	{{0, 1, L1, KEY_D}, {0x209}},
	{{0, 1, L2, KEY_G}, {0x20c}},
	{{0, 1, L1, KEY_G}, {0x20d}},
	{{0, 1, L2, KEY_S}, {0x210}},
	{{0, 1, L1, KEY_S}, {0x211}},
	{{0, 1, L2, KEY_E}, {0x214}},
	{{1, 1, L1, KEY_E}, {0x215}},
};

const Node Compose::NODE_1314732640832[] PROGMEM = {
	{{0, 1, L6, KEY_NON_US_NUM}, {0x311}},
	{{0, 1, L2, KEY_R}, {0x202}},
	{{0, 1, L1, KEY_R}, {0x203}},
	{{0, 1, L2, KEY_F}, {0x206}},
	{{0, 1, L1, KEY_F}, {0x207}},
	{{0, 1, L2, KEY_D}, {0x20a}},
	{{0, 1, L1, KEY_D}, {0x20b}},
	{{0, 1, L2, KEY_G}, {0x20e}},
	{{0, 1, L1, KEY_G}, {0x20f}},
	{{0, 1, L2, KEY_S}, {0x212}},
	{{0, 1, L1, KEY_S}, {0x213}},
	{{0, 1, L2, KEY_E}, {0x216}},
	{{1, 1, L1, KEY_E}, {0x217}},
};

const Node Compose::NODE_1314732812752[] PROGMEM = {
	{{0, 0, L1, KEY_S}, {(uint16_t) NODE_1314732812992}},
	{{0, 0, L1, KEY_R}, {(uint16_t) NODE_1314732813632}},
	{{0, 0, L5, KEY_R}, {(uint16_t) NODE_1314732813712}},
	{{0, 0, L1, KEY_SEMICOLON}, {(uint16_t) NODE_1314732814032}},
	{{0, 0, L2, KEY_LEFT_BRACE}, {(uint16_t) NODE_1314733164240}},
	{{0, 0, L1, KEY_LEFT_BRACE}, {(uint16_t) NODE_1314733164560}},
	{{0, 0, L1, KEY_D}, {(uint16_t) NODE_1314733167440}},
	{{0, 0, L3, KEY_PERIOD}, {(uint16_t) NODE_1314733169680}},
	{{0, 0, L1, KEY_L}, {(uint16_t) NODE_1314734293456}},
	{{1, 0, L1, KEY_Y}, {(uint16_t) NODE_1314734453072}},
};

const Node Compose::NODE_1314732812992[] PROGMEM = {
	{{0, 1, L1, KEY_S}, {0x27a}},
	{{1, 1, L3, KEY_W}, {0x27f}},
};

const Node Compose::NODE_1314732813632[] PROGMEM = {
	{{1, 1, L1, KEY_R}, {0x252}},
};

const Node Compose::NODE_1314732813712[] PROGMEM = {
	{{1, 1, L5, KEY_R}, {0x252}},
};

const Node Compose::NODE_1314732814032[] PROGMEM = {
	{{1, 1, L1, KEY_J}, {0x270}},
};

const Node Compose::NODE_1314733164240[] PROGMEM = {
	{{1, 1, L2, KEY_LEFT_BRACE}, {0x1b8}},
};

const Node Compose::NODE_1314733164560[] PROGMEM = {
	{{1, 1, L1, KEY_LEFT_BRACE}, {0x1b9}},
};

const Node Compose::NODE_1314733167440[] PROGMEM = {
	{{1, 1, L3, KEY_H}, {0x295}},
};

const Node Compose::NODE_1314733169680[] PROGMEM = {
	{{1, 1, L3, KEY_PERIOD}, {0x2cc}},
};

const Node Compose::NODE_1314734293456[] PROGMEM = {
	{{1, 1, L1, KEY_SEMICOLON}, {0x285}},
};

const Node Compose::NODE_1314734453072[] PROGMEM = {
	{{0, 1, L3, KEY_PERIOD}, {0x2035}},
	{{1, 1, L1, KEY_3}, {0x2037}},
};

const Node Compose::NODE_1314733171040[] PROGMEM = {
	{{0, 1, L3, KEY_EQUAL}, {0x325}},
	{{0, 1, L2, KEY_R}, {0x1e00}},
	{{1, 1, L1, KEY_R}, {0x1e01}},
};

const Node Compose::NODE_1314733171280[] PROGMEM = {
	{{0, 1, L4, KEY_EQUAL}, {0x324}},
	{{0, 1, L2, KEY_E}, {0x1e72}},
	{{1, 1, L1, KEY_E}, {0x1e73}},
};

const Node Compose::NODE_1314733171520[] PROGMEM = {
	{{0, 1, L2, KEY_NON_US_NUM}, {0x330}},
	{{0, 1, L2, KEY_F}, {0x1e1a}},
	{{0, 1, L1, KEY_F}, {0x1e1b}},
	{{0, 1, L2, KEY_D}, {0x1e2c}},
	{{0, 1, L1, KEY_D}, {0x1e2d}},
	{{0, 1, L2, KEY_E}, {0x1e74}},
	{{1, 1, L1, KEY_E}, {0x1e75}},
};

const Node Compose::NODE_1314734371232[] PROGMEM = {
	{{1, 1, L3, KEYPAD_6}, {0x21a9}},
};

const Node Compose::NODE_1314732443824[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2d9}},
	{{0, 1, L4, KEY_TILDE}, {0x307}},
	{{0, 1, L2, KEY_W}, {0x13f}},
	{{0, 1, L1, KEY_W}, {0x140}},
	{{0, 1, L1, KEY_Q}, {0x237}},
	{{0, 1, L1, KEY_SPACE}, {0x2d9}},
	{{0, 1, L2, KEY_A}, {0x10a}},
	{{0, 1, L1, KEY_A}, {0x10b}},
	{{0, 1, L2, KEY_F}, {0x116}},
	{{0, 1, L1, KEY_F}, {0x117}},
	{{0, 1, L2, KEY_O}, {0x120}},
	{{0, 1, L1, KEY_O}, {0x121}},
	{{0, 1, L2, KEY_D}, {0x130}},
	{{0, 1, L1, KEY_D}, {0x131}},
	{{0, 1, L2, KEY_LEFT_BRACE}, {0x17b}},
	{{0, 1, L1, KEY_LEFT_BRACE}, {0x17c}},
	{{0, 1, L2, KEY_R}, {0x226}},
	{{0, 1, L1, KEY_R}, {0x227}},
	{{0, 1, L2, KEY_G}, {0x22e}},
	{{0, 1, L1, KEY_G}, {0x22f}},
	{{0, 1, L2, KEY_U}, {0x1e02}},
	{{0, 1, L1, KEY_U}, {0x1e03}},
	{{0, 1, L2, KEY_I}, {0x1e0a}},
	{{0, 1, L1, KEY_I}, {0x1e0b}},
	{{0, 1, L2, KEY_M}, {0x1e1e}},
	{{0, 1, L1, KEY_M}, {0x1e1f}},
	{{0, 1, L2, KEY_SEMICOLON}, {0x1e22}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x1e23}},
	{{0, 1, L2, KEY_H}, {0x1e40}},
	{{0, 1, L1, KEY_H}, {0x1e41}},
	{{0, 1, L2, KEY_J}, {0x1e44}},
	{{0, 1, L1, KEY_J}, {0x1e45}},
	{{0, 1, L2, KEY_N}, {0x1e56}},
	{{0, 1, L1, KEY_N}, {0x1e57}},
	{{0, 1, L2, KEY_S}, {0x1e58}},
	{{0, 1, L1, KEY_S}, {0x1e59}},
	{{0, 1, L2, KEY_L}, {0x1e60}},
	{{0, 1, L1, KEY_L}, {0x1e61}},
	{{0, 0, L1, KEY_NON_US_NUM}, {(uint16_t) NODE_1314732953888}},
	{{0, 0, L2, KEY_TILDE}, {(uint16_t) NODE_1314732954128}},
	{{0, 1, L2, KEY_K}, {0x1e6a}},
	{{0, 1, L1, KEY_K}, {0x1e6b}},
	{{0, 1, L2, KEY_Y}, {0x1e86}},
	{{0, 1, L1, KEY_Y}, {0x1e87}},
	{{0, 1, L2, KEY_X}, {0x1e8a}},
	{{0, 1, L1, KEY_X}, {0x1e8b}},
	{{0, 1, L2, KEY_P}, {0x1e8e}},
	{{0, 1, L1, KEY_P}, {0x1e8f}},
	{{0, 1, L3, KEY_RIGHT_BRACE}, {0x1e9b}},
	{{0, 0, L3, KEY_TAB}, {(uint16_t) NODE_1314733028784}},
	{{0, 1, L1, KEY_0}, {0x298}},
	{{0, 1, L3, KEY_O}, {0x2250}},
	{{0, 1, L6, KEY_G}, {0x22f5}},
	{{0, 1, L6, KEY_3}, {0x2a51}},
	{{0, 1, L6, KEY_2}, {0x2a52}},
	{{0, 1, L3, KEY_V}, {0x2a6a}},
	{{0, 1, L1, KEY_MINUS}, {0x2238}},
	{{0, 1, L3, KEY_N}, {0x2214}},
	{{0, 1, L3, KEY_G}, {0x2a30}},
	{{1, 1, L6, KEY_I}, {0x29ca}},
};

const Node Compose::NODE_1314732953888[] PROGMEM = {
	{{0, 1, L2, KEY_L}, {0x1e64}},
	{{1, 1, L1, KEY_L}, {0x1e65}},
};

const Node Compose::NODE_1314732954128[] PROGMEM = {
	{{0, 1, L2, KEY_L}, {0x1e66}},
	{{1, 1, L1, KEY_L}, {0x1e67}},
};

const Node Compose::NODE_1314733028784[] PROGMEM = {
	{{0, 0, L1, KEY_M}, {(uint16_t) NODE_1314733028944}},
	{{1, 0, L3, KEY_O}, {(uint16_t) NODE_1314734302096}},
};

const Node Compose::NODE_1314733028944[] PROGMEM = {
	{{1, 1, L1, KEY_L}, {0x1e9b}},
};

const Node Compose::NODE_1314734302096[] PROGMEM = {
	{{1, 1, L3, KEY_O}, {0x2a67}},
};

const Node Compose::NODE_1314732444144[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2da}},
	{{0, 1, L3, KEY_EQUAL}, {0x30a}},
	{{0, 1, L1, KEY_SPACE}, {0xb0}},
	{{0, 1, L2, KEY_R}, {0xc5}},
	{{0, 1, L1, KEY_R}, {0xe5}},
	{{0, 1, L2, KEY_E}, {0x16e}},
	{{0, 1, L1, KEY_E}, {0x16f}},
	{{0, 1, L1, KEY_Y}, {0x1e98}},
	{{0, 1, L1, KEY_P}, {0x1e99}},
	{{0, 1, L1, KEY_A}, {0x255}},
	{{0, 1, L1, KEY_LEFT_BRACE}, {0x291}},
	{{0, 1, L1, KEY_I}, {0x221}},
	{{0, 1, L1, KEY_W}, {0x234}},
	{{0, 1, L1, KEY_J}, {0x235}},
	{{0, 1, L1, KEY_K}, {0x236}},
	{{0, 1, L6, KEY_D}, {0x222e}},
	{{0, 0, L1, KEY_2}, {(uint16_t) NODE_1314734299936}},
	{{0, 0, L1, KEY_3}, {(uint16_t) NODE_1314734300336}},
	{{0, 1, L3, KEY_O}, {0x2257}},
	{{0, 1, L3, KEY_N}, {0x2a22}},
	{{0, 1, L3, KEYPAD_4}, {0x21ab}},
	{{0, 0, L3, KEY_TILDE}, {(uint16_t) NODE_1314734441152}},
	{{1, 1, L3, KEYPAD_6}, {0x21ac}},
};

const Node Compose::NODE_1314734299936[] PROGMEM = {
	{{1, 1, L6, KEY_D}, {0x222f}},
};

const Node Compose::NODE_1314734300336[] PROGMEM = {
	{{1, 1, L6, KEY_D}, {0x2230}},
};

const Node Compose::NODE_1314734441152[] PROGMEM = {
	{{1, 1, L3, KEYPAD_6}, {0x21ab}},
};

const Node Compose::NODE_1314732444304[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2dc}},
	{{0, 1, L2, KEY_NON_US_NUM}, {0x303}},
	{{0, 1, L2, KEY_W}, {0x2c62}},
	{{0, 1, L1, KEY_W}, {0x26b}},
	{{0, 1, L1, KEY_SPACE}, {0x7e}},
	{{0, 1, L2, KEY_R}, {0xc3}},
	{{0, 1, L2, KEY_J}, {0xd1}},
	{{0, 1, L2, KEY_G}, {0xd5}},
	{{0, 1, L1, KEY_R}, {0xe3}},
	{{0, 1, L1, KEY_J}, {0xf1}},
	{{0, 1, L1, KEY_G}, {0xf5}},
	{{0, 1, L2, KEY_D}, {0x128}},
	{{0, 1, L1, KEY_D}, {0x129}},
	{{0, 1, L2, KEY_E}, {0x168}},
	{{0, 1, L1, KEY_E}, {0x169}},
	{{0, 1, L2, KEY_Z}, {0x1e7c}},
	{{0, 1, L1, KEY_Z}, {0x1e7d}},
	{{0, 0, L1, KEY_TILDE}, {(uint16_t) NODE_1314732958288}},
	{{0, 0, L6, KEY_NON_US_NUM}, {(uint16_t) NODE_1314732959568}},
	{{0, 1, L2, KEY_F}, {0x1ebc}},
	{{0, 1, L1, KEY_F}, {0x1ebd}},
	{{0, 0, L5, KEY_TILDE}, {(uint16_t) NODE_1314732963328}},
	{{0, 1, L2, KEY_P}, {0x1ef8}},
	{{0, 1, L1, KEY_P}, {0x1ef9}},
	{{0, 0, L5, KEY_NON_US_NUM}, {(uint16_t) NODE_1314733015664}},
	{{0, 0, L5, KEY_EQUAL}, {(uint16_t) NODE_1314733015824}},
	{{0, 1, L5, KEY_R}, {0x1fb6}},
	{{0, 1, L5, KEY_V}, {0x1fc6}},
	{{0, 1, L5, KEY_D}, {0x1fd6}},
	{{0, 0, L4, KEY_EQUAL}, {(uint16_t) NODE_1314733021424}},
	{{0, 1, L5, KEY_P}, {0x1fe6}},
	{{0, 1, L5, KEY_Y}, {0x1ff6}},
	{{0, 1, L3, KEY_O}, {0x2245}},
	{{0, 1, L3, KEY_V}, {0x2248}},
	{{0, 1, L1, KEY_MINUS}, {0x2243}},
	{{0, 1, L3, KEY_N}, {0x2a24}},
	{{0, 1, L3, KEYPAD_4}, {0x219c}},
	{{0, 0, L3, KEY_TILDE}, {(uint16_t) NODE_1314734440832}},
	{{1, 1, L3, KEYPAD_6}, {0x219d}},
};

const Node Compose::NODE_1314732958288[] PROGMEM = {
	{{0, 1, L2, KEY_R}, {0x1eaa}},
	{{0, 1, L1, KEY_R}, {0x1eab}},
	{{0, 1, L2, KEY_F}, {0x1ec4}},
	{{0, 1, L1, KEY_F}, {0x1ec5}},
	{{0, 1, L2, KEY_G}, {0x1ed6}},
	{{1, 1, L1, KEY_G}, {0x1ed7}},
};

const Node Compose::NODE_1314732959568[] PROGMEM = {
	{{0, 1, L2, KEY_R}, {0x1eb4}},
	{{1, 1, L1, KEY_R}, {0x1eb5}},
};

const Node Compose::NODE_1314732963328[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1ee0}},
	{{0, 1, L1, KEY_G}, {0x1ee1}},
	{{0, 1, L2, KEY_E}, {0x1eee}},
	{{1, 1, L1, KEY_E}, {0x1eef}},
};

const Node Compose::NODE_1314733015664[] PROGMEM = {
	{{0, 1, L5, KEY_R}, {0x1f06}},
	{{0, 1, L5, KEY_V}, {0x1f26}},
	{{0, 1, L5, KEY_D}, {0x1f36}},
	{{0, 1, L5, KEY_P}, {0x1f56}},
	{{0, 1, L5, KEY_Y}, {0x1f66}},
	{{1, 1, L6, KEY_Y}, {0x1f6e}},
};

const Node Compose::NODE_1314733015824[] PROGMEM = {
	{{0, 1, L5, KEY_R}, {0x1f07}},
	{{0, 1, L5, KEY_V}, {0x1f27}},
	{{0, 1, L5, KEY_D}, {0x1f37}},
	{{0, 1, L5, KEY_P}, {0x1f57}},
	{{0, 1, L5, KEY_Y}, {0x1f67}},
	{{1, 1, L6, KEY_Y}, {0x1f6f}},
};

const Node Compose::NODE_1314733021424[] PROGMEM = {
	{{0, 1, L5, KEY_D}, {0x1fd7}},
	{{1, 1, L5, KEY_P}, {0x1fe7}},
};

const Node Compose::NODE_1314734440832[] PROGMEM = {
	{{1, 1, L3, KEYPAD_6}, {0x219c}},
};

const Node Compose::NODE_1314732444624[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0xaf}},
	{{0, 1, L6, KEY_EQUAL}, {0x304}},
	{{0, 0, L2, KEY_EQUAL}, {(uint16_t) NODE_1314732691184}},
	{{0, 1, L2, KEY_U}, {0x1e06}},
	{{0, 1, L1, KEY_U}, {0x1e07}},
	{{0, 1, L2, KEY_I}, {0x1e0e}},
	{{0, 1, L1, KEY_I}, {0x1e0f}},
	{{0, 1, L2, KEY_SLASH}, {0x1e34}},
	{{0, 1, L1, KEY_SLASH}, {0x1e35}},
	{{0, 1, L2, KEY_W}, {0x1e3a}},
	{{0, 1, L1, KEY_W}, {0x1e3b}},
	{{0, 1, L2, KEY_J}, {0x1e48}},
	{{0, 1, L1, KEY_J}, {0x1e49}},
	{{0, 1, L2, KEY_S}, {0x1e5e}},
	{{0, 1, L1, KEY_S}, {0x1e5f}},
	{{0, 1, L2, KEY_K}, {0x1e6e}},
	{{0, 1, L1, KEY_K}, {0x1e6f}},
	{{0, 1, L2, KEY_LEFT_BRACE}, {0x1e94}},
	{{0, 1, L1, KEY_LEFT_BRACE}, {0x1e95}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x1e96}},
	{{0, 0, L3, KEY_TAB}, {(uint16_t) NODE_1314732697984}},
	{{0, 1, L1, KEY_SPACE}, {0xaf}},
	{{0, 1, L2, KEY_R}, {0x100}},
	{{0, 1, L1, KEY_R}, {0x101}},
	{{0, 1, L2, KEY_F}, {0x112}},
	{{0, 1, L1, KEY_F}, {0x113}},
	{{0, 1, L2, KEY_D}, {0x12a}},
	{{0, 1, L1, KEY_D}, {0x12b}},
	{{0, 1, L2, KEY_G}, {0x14c}},
	{{0, 1, L1, KEY_G}, {0x14d}},
	{{0, 1, L2, KEY_E}, {0x16a}},
	{{0, 1, L1, KEY_E}, {0x16b}},
	{{0, 1, L2, KEY_C}, {0x1d5}},
	{{0, 0, L4, KEY_EQUAL}, {(uint16_t) NODE_1314732877248}},
	{{0, 1, L1, KEY_C}, {0x1d6}},
	{{0, 1, L2, KEY_V}, {0x1de}},
	{{0, 1, L1, KEY_V}, {0x1df}},
	{{0, 0, L4, KEY_TILDE}, {(uint16_t) NODE_1314732879088}},
	{{0, 0, L2, KEY_NON_US_NUM}, {(uint16_t) NODE_1314732881168}},
	{{0, 1, L2, KEY_P}, {0x232}},
	{{0, 1, L1, KEY_P}, {0x233}},
	{{0, 1, L2, KEY_O}, {0x1e20}},
	{{0, 1, L1, KEY_O}, {0x1e21}},
	{{0, 0, L6, KEY_TILDE}, {(uint16_t) NODE_1314732950928}},
	{{0, 1, L5, KEY_R}, {0x1fb1}},
	{{0, 1, L5, KEY_D}, {0x1fd1}},
	{{0, 1, L5, KEY_P}, {0x1fe1}},
	{{0, 1, L3, KEY_V}, {0x2243}},
	{{0, 1, L3, KEY_U}, {0x2264}},
	{{0, 1, L3, KEY_I}, {0x2265}},
	{{0, 1, L6, KEY_3}, {0x22bc}},
	{{0, 1, L6, KEY_2}, {0x22bd}},
	{{0, 1, L6, KEY_A}, {0x2286}},
	{{0, 1, L6, KEY_D}, {0x2a1b}},
	{{0, 1, L6, KEY_C}, {0x2a42}},
	{{0, 1, L6, KEY_B}, {0x2a43}},
	{{1, 0, L1, KEY_N}, {(uint16_t) NODE_1314734451952}},
};

const Node Compose::NODE_1314732691184[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1ec}},
	{{1, 1, L1, KEY_G}, {0x1ed}},
};

const Node Compose::NODE_1314732697984[] PROGMEM = {
	{{0, 0, L2, KEY_R}, {(uint16_t) NODE_1314732698144}},
	{{1, 0, L1, KEY_R}, {(uint16_t) NODE_1314732698064}},
};

const Node Compose::NODE_1314732698144[] PROGMEM = {
	{{1, 1, L2, KEY_F}, {0x1e2}},
};

const Node Compose::NODE_1314732698064[] PROGMEM = {
	{{1, 1, L1, KEY_F}, {0x1e3}},
};

const Node Compose::NODE_1314732877248[] PROGMEM = {
	{{0, 1, L2, KEY_E}, {0x1d5}},
	{{0, 1, L1, KEY_E}, {0x1d6}},
	{{0, 1, L2, KEY_R}, {0x1de}},
	{{0, 1, L1, KEY_R}, {0x1df}},
	{{0, 1, L2, KEY_G}, {0x22a}},
	{{1, 1, L1, KEY_G}, {0x22b}},
};

const Node Compose::NODE_1314732879088[] PROGMEM = {
	{{0, 1, L2, KEY_R}, {0x1e0}},
	{{0, 1, L1, KEY_R}, {0x1e1}},
	{{0, 1, L2, KEY_G}, {0x230}},
	{{1, 1, L1, KEY_G}, {0x231}},
};

const Node Compose::NODE_1314732881168[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x22c}},
	{{1, 1, L1, KEY_G}, {0x22d}},
};

const Node Compose::NODE_1314732950928[] PROGMEM = {
	{{0, 1, L2, KEY_W}, {0x1e38}},
	{{0, 1, L1, KEY_W}, {0x1e39}},
	{{0, 1, L2, KEY_S}, {0x1e5c}},
	{{1, 1, L1, KEY_S}, {0x1e5d}},
};

const Node Compose::NODE_1314734451952[] PROGMEM = {
	{{1, 1, L1, KEY_SEMICOLON}, {0x210f}},
};

const Node Compose::NODE_1314732445264[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0xa8}},
	{{0, 1, L4, KEY_EQUAL}, {0x308}},
	{{0, 1, L1, KEY_SPACE}, {0xa8}},
	{{0, 1, L2, KEY_R}, {0xc4}},
	{{0, 1, L2, KEY_F}, {0xcb}},
	{{0, 1, L2, KEY_D}, {0xcf}},
	{{0, 1, L2, KEY_G}, {0xd6}},
	{{0, 1, L2, KEY_E}, {0xdc}},
	{{0, 1, L1, KEY_R}, {0xe4}},
	{{0, 1, L1, KEY_F}, {0xeb}},
	{{0, 1, L1, KEY_D}, {0xef}},
	{{0, 1, L1, KEY_G}, {0xf6}},
	{{0, 1, L1, KEY_E}, {0xfc}},
	{{0, 1, L1, KEY_P}, {0xff}},
	{{0, 1, L2, KEY_P}, {0x178}},
	{{0, 1, L2, KEY_SEMICOLON}, {0x1e26}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x1e27}},
	{{0, 0, L2, KEY_NON_US_NUM}, {(uint16_t) NODE_1314732952208}},
	{{0, 0, L6, KEY_EQUAL}, {(uint16_t) NODE_1314732954848}},
	{{0, 1, L2, KEY_Y}, {0x1e84}},
	{{0, 1, L1, KEY_Y}, {0x1e85}},
	{{0, 1, L2, KEY_X}, {0x1e8c}},
	{{0, 1, L1, KEY_X}, {0x1e8d}},
	{{1, 1, L1, KEY_K}, {0x1e97}},
};

const Node Compose::NODE_1314732952208[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1e4e}},
	{{1, 1, L1, KEY_G}, {0x1e4f}},
};

const Node Compose::NODE_1314732954848[] PROGMEM = {
	{{0, 1, L2, KEY_E}, {0x1e7a}},
	{{1, 1, L1, KEY_E}, {0x1e7b}},
};

const Node Compose::NODE_1314732445584[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2f}},
	{{0, 1, L3, KEY_NON_US_NUM}, {0x337}},
	{{0, 1, L1, KEY_SPACE}, {0x2010}},
	{{0, 1, L2, KEY_I}, {0x110}},
	{{0, 1, L1, KEY_I}, {0x111}},
	{{0, 1, L2, KEY_SEMICOLON}, {0x126}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x127}},
	{{0, 1, L2, KEY_W}, {0x141}},
	{{0, 1, L1, KEY_W}, {0x142}},
	{{0, 1, L2, KEY_G}, {0xd8}},
	{{0, 1, L1, KEY_G}, {0xf8}},
	{{0, 1, L5, KEY_4}, {0x26a6}},
	{{0, 1, L5, KEY_6}, {0x26a7}},
	{{0, 1, L3, KEY_S}, {0x2718}},
	{{0, 1, L3, KEY_A}, {0x2718}},
	{{0, 1, L4, KEY_6}, {0x20a4}},
	{{0, 1, L2, KEY_K}, {0x166}},
	{{0, 1, L1, KEY_K}, {0x167}},
	{{0, 1, L1, KEY_U}, {0x180}},
	{{0, 1, L2, KEY_D}, {0x197}},
	{{0, 1, L2, KEY_LEFT_BRACE}, {0x1b5}},
	{{0, 1, L1, KEY_LEFT_BRACE}, {0x1b6}},
	{{0, 1, L2, KEY_O}, {0x1e4}},
	{{0, 1, L1, KEY_O}, {0x1e5}},
	{{0, 0, L1, KEY_NON_US_NUM}, {(uint16_t) NODE_1314732880528}},
	{{0, 1, L1, KEY_D}, {0x268}},
	{{0, 1, L2, KEY_R}, {0x23a}},
	{{0, 1, L1, KEY_R}, {0x2c65}},
	{{0, 1, L2, KEY_U}, {0x243}},
	{{0, 1, L2, KEY_A}, {0x23b}},
	{{0, 1, L1, KEY_A}, {0x23c}},
	{{0, 1, L2, KEY_F}, {0x246}},
	{{0, 1, L1, KEY_F}, {0x247}},
	{{0, 0, L3, KEY_TAB}, {(uint16_t) NODE_1314733095040}},
	{{0, 1, L2, KEY_Q}, {0x25f}},
	{{0, 1, L1, KEY_Q}, {0x25f}},
	{{0, 0, L4, KEY_TILDE}, {(uint16_t) NODE_1314733095680}},
	{{0, 1, L2, KEY_N}, {0x2c63}},
	{{0, 0, L1, KEY_N}, {(uint16_t) NODE_1314733096400}},
	{{0, 1, L2, KEY_S}, {0x24c}},
	{{0, 1, L1, KEY_S}, {0x24d}},
	{{0, 1, L1, KEY_E}, {0x289}},
	{{0, 1, L2, KEY_E}, {0x244}},
	{{0, 1, L2, KEY_P}, {0x24e}},
	{{0, 1, L1, KEY_P}, {0x24f}},
	{{0, 1, L5, KEY_W}, {0x19b}},
	{{0, 1, L5, KEY_D}, {0x1d7c}},
	{{0, 1, L5, KEY_P}, {0x1d7f}},
	{{0, 0, L3, KEY_TILDE}, {(uint16_t) NODE_1314733167200}},
	{{0, 1, L3, KEY_RIGHT_BRACE}, {0x1e9c}},
	{{0, 1, L1, KEY_0}, {0x2205}},
	{{0, 1, L6, KEY_D}, {0x2a0f}},
	{{0, 1, L3, KEY_O}, {0x2260}},
	{{0, 1, L3, KEYPAD_4}, {0x219a}},
	{{0, 1, L3, KEYPAD_6}, {0x219b}},
	{{0, 1, L6, KEY_G}, {0x2209}},
	{{0, 1, L3, KEY_C}, {0x2224}},
	{{0, 1, L3, KEY_V}, {0x2241}},
	{{0, 1, L3, KEY_U}, {0x226e}},
	{{0, 1, L3, KEY_I}, {0x226f}},
	{{1, 1, L6, KEY_A}, {0x2284}},
};

const Node Compose::NODE_1314732880528[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1fe}},
	{{1, 1, L1, KEY_G}, {0x1ff}},
};

const Node Compose::NODE_1314733095040[] PROGMEM = {
	{{0, 0, L2, KEY_D}, {(uint16_t) NODE_1314733095200}},
	{{0, 0, L2, KEY_E}, {(uint16_t) NODE_1314733163680}},
	{{0, 0, L1, KEY_D}, {(uint16_t) NODE_1314733167360}},
	{{0, 0, L6, KEY_G}, {(uint16_t) NODE_1314734364192}},
	{{0, 0, L3, KEY_U}, {(uint16_t) NODE_1314734365872}},
	{{0, 0, L3, KEY_C}, {(uint16_t) NODE_1314734366032}},
	{{1, 0, L3, KEY_O}, {(uint16_t) NODE_1314734366192}},
};

const Node Compose::NODE_1314733095200[] PROGMEM = {
	{{1, 1, L2, KEY_D}, {0x1d7b}},
};

const Node Compose::NODE_1314733163680[] PROGMEM = {
	{{1, 1, L2, KEY_E}, {0x1d7e}},
};

const Node Compose::NODE_1314733167360[] PROGMEM = {
	{{1, 1, L3, KEY_H}, {0x2a1}},
};

const Node Compose::NODE_1314734364192[] PROGMEM = {
	{{1, 1, L6, KEY_G}, {0x220c}},
};

const Node Compose::NODE_1314734365872[] PROGMEM = {
	{{1, 1, L3, KEY_C}, {0x22ea}},
};

const Node Compose::NODE_1314734366032[] PROGMEM = {
	{{0, 1, L3, KEY_I}, {0x22eb}},
	{{0, 1, L1, KEY_MINUS}, {0x22ac}},
	{{1, 1, L3, KEY_O}, {0x22ad}},
};

const Node Compose::NODE_1314734366192[] PROGMEM = {
	{{0, 0, L3, KEY_U}, {(uint16_t) NODE_1314734366432}},
	{{1, 0, L3, KEY_C}, {(uint16_t) NODE_1314734366592}},
};

const Node Compose::NODE_1314734366432[] PROGMEM = {
	{{1, 1, L3, KEY_C}, {0x22ec}},
};

const Node Compose::NODE_1314734366592[] PROGMEM = {
	{{1, 1, L3, KEY_I}, {0x22ed}},
};

const Node Compose::NODE_1314733095680[] PROGMEM = {
	{{1, 1, L1, KEY_Q}, {0x25f}},
};

const Node Compose::NODE_1314733096400[] PROGMEM = {
	{{1, 1, L1, KEY_SEMICOLON}, {0x210f}},
};

const Node Compose::NODE_1314733167200[] PROGMEM = {
	{{0, 1, L3, KEY_H}, {0x2a2}},
	{{0, 0, L3, KEY_TAB}, {(uint16_t) NODE_1314733167680}},
	{{1, 1, L6, KEY_G}, {0x220c}},
};

const Node Compose::NODE_1314733167680[] PROGMEM = {
	{{1, 0, L1, KEY_D}, {(uint16_t) NODE_1314733167920}},
};

const Node Compose::NODE_1314733167920[] PROGMEM = {
	{{1, 1, L3, KEY_H}, {0x2a2}},
};

const Node Compose::NODE_1314732446144[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2dd}},
	{{0, 1, L4, KEY_NON_US_NUM}, {0x30b}},
	{{0, 1, L1, KEY_SPACE}, {0x2dd}},
	{{0, 1, L2, KEY_G}, {0x150}},
	{{0, 1, L1, KEY_G}, {0x151}},
	{{0, 1, L2, KEY_E}, {0x170}},
	{{1, 1, L1, KEY_E}, {0x171}},
};

const Node Compose::NODE_1314732445904[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x1fbf}},
	{{0, 1, L5, KEY_NON_US_NUM}, {0x313}},
	{{0, 1, L1, KEY_SPACE}, {0x1fbf}},
	{{0, 1, L2, KEY_R}, {0x1ea2}},
	{{0, 1, L1, KEY_R}, {0x1ea3}},
	{{0, 0, L1, KEY_TILDE}, {(uint16_t) NODE_1314732958048}},
	{{0, 0, L6, KEY_NON_US_NUM}, {(uint16_t) NODE_1314732959328}},
	{{0, 1, L2, KEY_F}, {0x1eba}},
	{{0, 1, L1, KEY_F}, {0x1ebb}},
	{{0, 1, L2, KEY_D}, {0x1ec8}},
	{{0, 1, L1, KEY_D}, {0x1ec9}},
	{{0, 1, L2, KEY_G}, {0x1ece}},
	{{0, 1, L1, KEY_G}, {0x1ecf}},
	{{0, 0, L5, KEY_TILDE}, {(uint16_t) NODE_1314732963248}},
	{{0, 1, L2, KEY_E}, {0x1ee6}},
	{{0, 1, L1, KEY_E}, {0x1ee7}},
	{{0, 1, L2, KEY_P}, {0x1ef6}},
	{{0, 1, L1, KEY_P}, {0x1ef7}},
	{{0, 1, L5, KEY_R}, {0x1f00}},
	{{0, 1, L5, KEY_F}, {0x1f10}},
	{{0, 1, L5, KEY_V}, {0x1f20}},
	{{0, 1, L5, KEY_D}, {0x1f30}},
	{{0, 1, L5, KEY_G}, {0x1f40}},
	{{0, 1, L5, KEY_P}, {0x1f50}},
	{{0, 1, L5, KEY_Y}, {0x1f60}},
	{{0, 1, L6, KEY_Y}, {0x1f68}},
	{{0, 1, L5, KEY_S}, {0x1fe4}},
	{{1, 0, L3, KEY_TILDE}, {(uint16_t) NODE_1314734293696}},
};

const Node Compose::NODE_1314732958048[] PROGMEM = {
	{{0, 1, L2, KEY_R}, {0x1ea8}},
	{{0, 1, L1, KEY_R}, {0x1ea9}},
	{{0, 1, L2, KEY_F}, {0x1ec2}},
	{{0, 1, L1, KEY_F}, {0x1ec3}},
	{{0, 1, L2, KEY_G}, {0x1ed4}},
	{{1, 1, L1, KEY_G}, {0x1ed5}},
};

const Node Compose::NODE_1314732959328[] PROGMEM = {
	{{0, 1, L2, KEY_R}, {0x1eb2}},
	{{1, 1, L1, KEY_R}, {0x1eb3}},
};

const Node Compose::NODE_1314732963248[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1ede}},
	{{0, 1, L1, KEY_G}, {0x1edf}},
	{{0, 1, L2, KEY_E}, {0x1eec}},
	{{1, 1, L1, KEY_E}, {0x1eed}},
};

const Node Compose::NODE_1314734293696[] PROGMEM = {
	{{1, 1, L1, KEY_SEMICOLON}, {0x2ae}},
};

const Node Compose::NODE_1314732445744[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x1ffe}},
	{{0, 1, L5, KEY_EQUAL}, {0x314}},
	{{0, 1, L1, KEY_SPACE}, {0x1ffe}},
	{{0, 1, L5, KEY_R}, {0x1f01}},
	{{0, 1, L5, KEY_F}, {0x1f11}},
	{{0, 1, L5, KEY_V}, {0x1f21}},
	{{0, 1, L5, KEY_D}, {0x1f31}},
	{{0, 1, L5, KEY_G}, {0x1f41}},
	{{0, 1, L5, KEY_P}, {0x1f51}},
	{{0, 1, L5, KEY_Y}, {0x1f61}},
	{{0, 1, L6, KEY_Y}, {0x1f69}},
	{{0, 1, L5, KEY_S}, {0x1fe5}},
	{{1, 0, L5, KEY_NON_US_NUM}, {(uint16_t) NODE_1314734293856}},
};

const Node Compose::NODE_1314734293856[] PROGMEM = {
	{{1, 0, L3, KEY_TILDE}, {(uint16_t) NODE_1314734294176}},
};

const Node Compose::NODE_1314734294176[] PROGMEM = {
	{{1, 1, L1, KEY_SEMICOLON}, {0x2af}},
};

const Node Compose::NODE_1314732446544[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2de}},
	{{0, 1, L5, KEY_TILDE}, {0x2de}},
	{{0, 1, L1, KEY_SPACE}, {0x2de}},
	{{0, 1, L3, KEY_S}, {0x2714}},
	{{0, 1, L3, KEY_A}, {0x2714}},
	{{0, 1, L2, KEY_G}, {0x1a0}},
	{{0, 1, L1, KEY_G}, {0x1a1}},
	{{0, 1, L2, KEY_E}, {0x1af}},
	{{0, 1, L1, KEY_E}, {0x1b0}},
	{{0, 1, L2, KEY_U}, {0x181}},
	{{0, 1, L1, KEY_U}, {0x253}},
	{{0, 1, L2, KEY_A}, {0x187}},
	{{0, 1, L1, KEY_A}, {0x188}},
	{{0, 1, L2, KEY_I}, {0x18a}},
	{{0, 1, L1, KEY_I}, {0x257}},
	{{0, 1, L2, KEY_M}, {0x191}},
	{{0, 1, L1, KEY_M}, {0x192}},
	{{0, 0, L3, KEY_TAB}, {(uint16_t) NODE_1314733089280}},
	{{0, 1, L2, KEY_O}, {0x193}},
	{{0, 1, L1, KEY_O}, {0x260}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x266}},
	{{0, 1, L2, KEY_D}, {0x196}},
	{{0, 1, L1, KEY_D}, {0x269}},
	{{0, 1, L1, KEY_Q}, {0x29d}},
	{{0, 1, L2, KEY_SLASH}, {0x198}},
	{{0, 1, L1, KEY_SLASH}, {0x199}},
	{{0, 1, L1, KEY_W}, {0x26c}},
	{{0, 1, L2, KEY_H}, {0x2c6e}},
	{{0, 1, L1, KEY_H}, {0x271}},
	{{0, 1, L2, KEY_J}, {0x14a}},
	{{0, 1, L1, KEY_J}, {0x14b}},
	{{0, 1, L2, KEY_N}, {0x1a4}},
	{{0, 1, L1, KEY_N}, {0x1a5}},
	{{0, 1, L2, KEY_S}, {0x2c64}},
	{{0, 1, L1, KEY_S}, {0x27d}},
	{{0, 1, L1, KEY_L}, {0x282}},
	{{0, 1, L2, KEY_K}, {0x1ac}},
	{{0, 1, L1, KEY_K}, {0x1ad}},
	{{0, 1, L1, KEY_Z}, {0x2c71}},
	{{0, 1, L2, KEY_Y}, {0x2c72}},
	{{0, 1, L1, KEY_Y}, {0x2c73}},
	{{0, 1, L2, KEY_X}, {0x194}},
	{{0, 1, L1, KEY_X}, {0x263}},
	{{0, 1, L2, KEY_P}, {0x1b3}},
	{{0, 1, L1, KEY_P}, {0x1b4}},
	{{0, 1, L1, KEY_LEFT_BRACE}, {0x290}},
	{{0, 1, L1, KEY_3}, {0x25d}},
	{{0, 0, L3, KEY_TILDE}, {(uint16_t) NODE_1314733092880}},
	{{0, 0, L3, KEY_NON_US_NUM}, {(uint16_t) NODE_1314733095760}},
	{{0, 1, L3, KEYPAD_6}, {0x21aa}},
	{{1, 1, L3, KEYPAD_4}, {0x21a9}},
};

const Node Compose::NODE_1314733089280[] PROGMEM = {
	{{0, 0, L2, KEY_O}, {(uint16_t) NODE_1314733089440}},
	{{0, 0, L1, KEY_F}, {(uint16_t) NODE_1314733092000}},
	{{0, 0, L1, KEY_MINUS}, {(uint16_t) NODE_1314734370752}},
	{{0, 0, L3, KEY_U}, {(uint16_t) NODE_1314734370992}},
	{{0, 0, L3, KEY_A}, {(uint16_t) NODE_1314734371312}},
	{{1, 0, L3, KEY_S}, {(uint16_t) NODE_1314734371472}},
};

const Node Compose::NODE_1314733089440[] PROGMEM = {
	{{1, 1, L2, KEY_O}, {0x29b}},
};

const Node Compose::NODE_1314733092000[] PROGMEM = {
	{{1, 1, L1, KEY_F}, {0x25a}},
};

const Node Compose::NODE_1314734370752[] PROGMEM = {
	{{1, 1, L3, KEY_I}, {0x21aa}},
};

const Node Compose::NODE_1314734370992[] PROGMEM = {
	{{1, 1, L1, KEY_MINUS}, {0x21a9}},
};

const Node Compose::NODE_1314734371312[] PROGMEM = {
	{{0, 1, L3, KEY_T}, {0x2923}},
	{{1, 1, L1, KEY_Z}, {0x2925}},
};

const Node Compose::NODE_1314734371472[] PROGMEM = {
	{{0, 1, L3, KEY_T}, {0x2924}},
	{{1, 1, L1, KEY_Z}, {0x2926}},
};

const Node Compose::NODE_1314733092880[] PROGMEM = {
	{{0, 1, L1, KEY_S}, {0x27b}},
	{{1, 1, L3, KEYPAD_6}, {0x21a9}},
};

const Node Compose::NODE_1314733095760[] PROGMEM = {
	{{1, 1, L2, KEY_Q}, {0x284}},
};

const Node Compose::NODE_1314732641952[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2e}},
	{{0, 1, L6, KEY_TILDE}, {0x323}},
	{{0, 1, L1, KEY_SPACE}, {0x2e}},
	{{0, 1, L2, KEY_U}, {0x1e04}},
	{{0, 1, L1, KEY_U}, {0x1e05}},
	{{0, 1, L2, KEY_I}, {0x1e0c}},
	{{0, 1, L1, KEY_I}, {0x1e0d}},
	{{0, 1, L2, KEY_SEMICOLON}, {0x1e24}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x1e25}},
	{{0, 1, L2, KEY_SLASH}, {0x1e32}},
	{{0, 1, L1, KEY_SLASH}, {0x1e33}},
	{{0, 1, L2, KEY_W}, {0x1e36}},
	{{0, 1, L1, KEY_W}, {0x1e37}},
	{{0, 1, L2, KEY_H}, {0x1e42}},
	{{0, 1, L1, KEY_H}, {0x1e43}},
	{{0, 1, L2, KEY_J}, {0x1e46}},
	{{0, 1, L1, KEY_J}, {0x1e47}},
	{{0, 1, L2, KEY_S}, {0x1e5a}},
	{{0, 1, L1, KEY_S}, {0x1e5b}},
	{{0, 1, L2, KEY_L}, {0x1e62}},
	{{0, 1, L1, KEY_L}, {0x1e63}},
	{{0, 1, L2, KEY_K}, {0x1e6c}},
	{{0, 1, L1, KEY_K}, {0x1e6d}},
	{{0, 1, L2, KEY_Z}, {0x1e7e}},
	{{0, 1, L1, KEY_Z}, {0x1e7f}},
	{{0, 1, L2, KEY_Y}, {0x1e88}},
	{{0, 1, L1, KEY_Y}, {0x1e89}},
	{{0, 1, L2, KEY_LEFT_BRACE}, {0x1e92}},
	{{0, 1, L1, KEY_LEFT_BRACE}, {0x1e93}},
	{{0, 1, L2, KEY_R}, {0x1ea0}},
	{{0, 1, L1, KEY_R}, {0x1ea1}},
	{{0, 1, L2, KEY_F}, {0x1eb8}},
	{{0, 1, L1, KEY_F}, {0x1eb9}},
	{{0, 1, L2, KEY_D}, {0x1eca}},
	{{0, 1, L1, KEY_D}, {0x1ecb}},
	{{0, 1, L2, KEY_G}, {0x1ecc}},
	{{0, 1, L1, KEY_G}, {0x1ecd}},
	{{0, 0, L5, KEY_TILDE}, {(uint16_t) NODE_1314732963728}},
	{{0, 1, L2, KEY_E}, {0x1ee4}},
	{{0, 1, L1, KEY_E}, {0x1ee5}},
	{{0, 1, L2, KEY_P}, {0x1ef4}},
	{{0, 1, L1, KEY_P}, {0x1ef5}},
	{{0, 1, L3, KEY_O}, {0x2a66}},
	{{1, 1, L6, KEY_3}, {0x27d1}},
};

const Node Compose::NODE_1314732963728[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1ee2}},
	{{0, 1, L1, KEY_G}, {0x1ee3}},
	{{0, 1, L2, KEY_E}, {0x1ef0}},
	{{1, 1, L1, KEY_E}, {0x1ef1}},
};

const Node Compose::NODE_1314732641552[] PROGMEM = {
	{{0, 0, L1, KEY_G}, {(uint16_t) NODE_1314732641392}},
	{{0, 0, L3, KEY_Q}, {(uint16_t) NODE_1314732638992}},
	{{0, 0, L3, KEY_W}, {(uint16_t) NODE_1314732689104}},
	{{0, 0, L3, KEY_0}, {(uint16_t) NODE_1314732689344}},
	{{0, 0, L1, KEY_MINUS}, {(uint16_t) NODE_1314732693184}},
	{{0, 0, L2, KEY_L}, {(uint16_t) NODE_1314732695024}},
	{{0, 0, L1, KEY_L}, {(uint16_t) NODE_1314732695184}},
	{{0, 0, L2, KEY_K}, {(uint16_t) NODE_1314732695264}},
	{{0, 0, L1, KEY_K}, {(uint16_t) NODE_1314732695424}},
	{{0, 0, L2, KEY_F}, {(uint16_t) NODE_1314732696624}},
	{{0, 0, L2, KEY_W}, {(uint16_t) NODE_1314732696704}},
	{{0, 0, L1, KEY_W}, {(uint16_t) NODE_1314732696864}},
	{{0, 0, L1, KEY_D}, {(uint16_t) NODE_1314732697584}},
	{{0, 0, L2, KEY_D}, {(uint16_t) NODE_1314732697664}},
	{{0, 0, L1, KEY_LEFT_BRACE}, {(uint16_t) NODE_1314732698704}},
	{{0, 0, L1, KEY_M}, {(uint16_t) NODE_1314732699024}},
	{{0, 0, L2, KEY_M}, {(uint16_t) NODE_1314732699344}},
	{{0, 0, L3, KEY_RIGHT_BRACE}, {(uint16_t) NODE_1314732699584}},
	{{0, 0, L2, KEY_I}, {(uint16_t) NODE_1314732699984}},
	{{0, 0, L1, KEY_I}, {(uint16_t) NODE_1314732700224}},
	{{0, 0, L2, KEY_J}, {(uint16_t) NODE_1314732701104}},
	{{0, 0, L1, KEY_J}, {(uint16_t) NODE_1314732701344}},
	{{0, 0, L1, KEY_2}, {(uint16_t) NODE_1314732702464}},
	{{0, 0, L3, KEY_Y}, {(uint16_t) NODE_1314732702384}},
	{{0, 0, L3, KEY_H}, {(uint16_t) NODE_1314732702704}},
	{{0, 0, L1, KEY_1}, {(uint16_t) NODE_1314732703024}},
	{{0, 0, L2, KEYPAD_9}, {(uint16_t) NODE_1314732703664}},
	{{0, 0, L5, KEY_SPACE}, {(uint16_t) NODE_1314732802432}},
	{{0, 0, L1, KEY_7}, {(uint16_t) NODE_1314732802672}},
	{{0, 0, L2, KEY_S}, {(uint16_t) NODE_1314732802592}},
	{{0, 0, L1, KEY_S}, {(uint16_t) NODE_1314732803872}},
	{{0, 0, L1, KEY_3}, {(uint16_t) NODE_1314732805312}},
	{{0, 0, L1, KEY_4}, {(uint16_t) NODE_1314732805392}},
	{{0, 0, L1, KEY_5}, {(uint16_t) NODE_1314732805712}},
	{{0, 0, L3, KEY_SEMICOLON}, {(uint16_t) NODE_1314732806592}},
	{{0, 0, L1, KEY_A}, {(uint16_t) NODE_1314732806832}},
	{{0, 0, L5, KEY_5}, {(uint16_t) NODE_1314732806912}},
	{{0, 0, L5, KEY_4}, {(uint16_t) NODE_1314732807152}},
	{{0, 1, L1, KEY_TAB}, {0x266b}},
	{{0, 1, L3, KEY_TAB}, {0x266b}},
	{{0, 0, L3, KEY_U}, {(uint16_t) NODE_1314732808272}},
	{{0, 0, L2, KEY_A}, {(uint16_t) NODE_1314732808592}},
	{{0, 0, L3, KEY_E}, {(uint16_t) NODE_1314732808432}},
	{{0, 0, L6, KEYPAD_0}, {(uint16_t) NODE_1314732808832}},
	{{0, 0, L2, KEYPAD_7}, {(uint16_t) NODE_1314732808992}},
	{{0, 0, L2, KEYPAD_8}, {(uint16_t) NODE_1314732809312}},
	{{0, 0, L6, KEY_I}, {(uint16_t) NODE_1314732809392}},
	{{0, 0, L2, KEYPAD_0}, {(uint16_t) NODE_1314732809792}},
	{{0, 0, L1, KEY_N}, {(uint16_t) NODE_1314732809872}},
	{{0, 0, L1, KEY_PERIOD}, {(uint16_t) NODE_1314732810832}},
	{{0, 0, L2, KEY_PERIOD}, {(uint16_t) NODE_1314732811152}},
	{{0, 0, L2, KEY_G}, {(uint16_t) NODE_1314733022464}},
	{{0, 0, L3, KEY_N}, {(uint16_t) NODE_1314733023344}},
	{{0, 0, L2, KEY_N}, {(uint16_t) NODE_1314733023664}},
	{{0, 0, L3, KEY_S}, {(uint16_t) NODE_1314733024144}},
	{{0, 0, L3, KEY_O}, {(uint16_t) NODE_1314733024544}},
	{{0, 0, L1, KEY_H}, {(uint16_t) NODE_1314733024624}},
	{{0, 0, L2, KEY_Y}, {(uint16_t) NODE_1314733025264}},
	{{0, 0, L1, KEY_F}, {(uint16_t) NODE_1314733026224}},
	{{0, 0, L3, KEY_C}, {(uint16_t) NODE_1314733027104}},
	{{0, 0, L2, KEY_P}, {(uint16_t) NODE_1314733027904}},
	{{0, 0, L1, KEY_P}, {(uint16_t) NODE_1314733028144}},
	{{0, 0, L4, KEY_TILDE}, {(uint16_t) NODE_1314733028864}},
	{{0, 0, L3, KEY_Z}, {(uint16_t) NODE_1314733029504}},
	{{0, 0, L1, KEY_X}, {(uint16_t) NODE_1314733030704}},
	{{0, 0, L2, KEY_X}, {(uint16_t) NODE_1314733030944}},
	{{0, 0, L1, KEY_R}, {(uint16_t) NODE_1314733081520}},
	{{0, 0, L2, KEY_R}, {(uint16_t) NODE_1314733081600}},
	{{0, 0, L1, KEY_0}, {(uint16_t) NODE_1314733082320}},
	{{0, 0, L3, KEY_T}, {(uint16_t) NODE_1314733082640}},
	{{0, 0, L5, KEY_O}, {(uint16_t) NODE_1314733091520}},
	{{0, 0, L2, KEY_Z}, {(uint16_t) NODE_1314733092240}},
	{{0, 0, L1, KEY_Z}, {(uint16_t) NODE_1314733092080}},
	{{0, 0, L1, KEY_Q}, {(uint16_t) NODE_1314733093040}},
	{{0, 0, L2, KEY_Q}, {(uint16_t) NODE_1314733093200}},
	{{0, 0, L5, KEY_TILDE}, {(uint16_t) NODE_1314733093680}},
	{{0, 0, L2, KEY_LEFT_BRACE}, {(uint16_t) NODE_1314733163920}},
	{{0, 0, L2, KEY_U}, {(uint16_t) NODE_1314733165040}},
	{{0, 0, L2, KEY_O}, {(uint16_t) NODE_1314733165120}},
	{{0, 0, L2, KEY_SEMICOLON}, {(uint16_t) NODE_1314733165280}},
	{{0, 0, L5, KEY_R}, {(uint16_t) NODE_1314733165920}},
	{{0, 0, L5, KEY_F}, {(uint16_t) NODE_1314733166080}},
	{{0, 0, L5, KEY_T}, {(uint16_t) NODE_1314733166240}},
	{{0, 0, L5, KEY_P}, {(uint16_t) NODE_1314733166400}},
	{{0, 0, L1, KEY_O}, {(uint16_t) NODE_1314733167840}},
	{{0, 0, L3, KEY_J}, {(uint16_t) NODE_1314733168400}},
	{{0, 0, L3, KEY_PERIOD}, {(uint16_t) NODE_1314733169200}},
	{{0, 0, L6, KEY_EQUAL}, {(uint16_t) NODE_1314733172960}},
	{{0, 0, L1, KEY_EQUAL}, {(uint16_t) NODE_1314733173040}},
	{{0, 0, L1, KEY_NON_US_NUM}, {(uint16_t) NODE_1314733173200}},
	{{0, 0, L5, KEY_G}, {(uint16_t) NODE_1314734296416}},
	{{0, 0, L1, KEY_SEMICOLON}, {(uint16_t) NODE_1314734298016}},
	{{0, 0, L1, KEY_Y}, {(uint16_t) NODE_1314734298336}},
	{{0, 0, L6, KEY_Z}, {(uint16_t) NODE_1314734298736}},
	{{0, 0, L6, KEY_D}, {(uint16_t) NODE_1314734299216}},
	{{0, 0, L3, KEY_I}, {(uint16_t) NODE_1314734300896}},
	{{0, 0, L3, KEY_V}, {(uint16_t) NODE_1314734301456}},
	{{0, 0, L2, KEY_1}, {(uint16_t) NODE_1314734302976}},
	{{0, 0, L6, KEY_G}, {(uint16_t) NODE_1314734305136}},
	{{0, 0, L6, KEY_2}, {(uint16_t) NODE_1314734306016}},
	{{0, 0, L6, KEY_3}, {(uint16_t) NODE_1314734306256}},
	{{0, 0, L6, KEY_C}, {(uint16_t) NODE_1314734306496}},
	{{0, 0, L6, KEY_B}, {(uint16_t) NODE_1314734306656}},
	{{0, 0, L6, KEY_L}, {(uint16_t) NODE_1314734306576}},
	{{0, 0, L6, KEY_N}, {(uint16_t) NODE_1314734306896}},
	{{0, 0, L6, KEY_A}, {(uint16_t) NODE_1314734307216}},
	{{0, 0, L3, KEY_A}, {(uint16_t) NODE_1314734308656}},
	{{0, 0, L3, KEY_G}, {(uint16_t) NODE_1314734309296}},
	{{0, 0, L3, KEYPAD_4}, {(uint16_t) NODE_1314734367312}},
	{{0, 0, L3, KEYPAD_8}, {(uint16_t) NODE_1314734368352}},
	{{0, 0, L3, KEYPAD_2}, {(uint16_t) NODE_1314734368592}},
	{{0, 0, L3, KEYPAD_6}, {(uint16_t) NODE_1314734368672}},
	{{0, 0, L3, KEY_TILDE}, {(uint16_t) NODE_1314734373152}},
	{{0, 0, L3, KEY_K}, {(uint16_t) NODE_1314734450592}},
	{{0, 0, L3, KEY_R}, {(uint16_t) NODE_1314734450992}},
	{{1, 0, L3, KEY_F}, {(uint16_t) NODE_1314734451312}},
};

const Node Compose::NODE_1314732641392[] PROGMEM = {
	{{0, 1, L1, KEY_SPACE}, {0x25cc}},
	{{0, 0, L1, KEY_N}, {(uint16_t) NODE_1314732810352}},
	{{0, 1, L1, KEY_A}, {0xa9}},
	{{0, 1, L2, KEY_A}, {0xa9}},
	{{0, 1, L1, KEY_S}, {0xae}},
	{{0, 1, L2, KEY_S}, {0xae}},
	{{0, 1, L1, KEY_L}, {0xa7}},
	{{0, 1, L1, KEY_X}, {0xa4}},
	{{0, 1, L2, KEY_X}, {0xa4}},
	{{0, 1, L1, KEY_F}, {0x153}},
	{{0, 1, L6, KEY_D}, {0x222e}},
	{{0, 0, L1, KEY_2}, {(uint16_t) NODE_1314734300176}},
	{{0, 0, L1, KEY_3}, {(uint16_t) NODE_1314734300496}},
	{{0, 1, L3, KEY_N}, {0x2295}},
	{{0, 1, L1, KEY_MINUS}, {0x2296}},
	{{0, 1, L3, KEY_G}, {0x2297}},
	{{0, 1, L3, KEY_S}, {0x2298}},
	{{0, 1, L1, KEY_PERIOD}, {0x2299}},
	{{0, 1, L2, KEY_1}, {0x229a}},
	{{0, 1, L3, KEY_O}, {0x229c}},
	{{0, 1, L3, KEY_U}, {0x29c0}},
	{{1, 1, L3, KEY_I}, {0x29c1}},
};

const Node Compose::NODE_1314732810352[] PROGMEM = {
	{{1, 1, L1, KEY_K}, {0x2325}},
};

const Node Compose::NODE_1314734300176[] PROGMEM = {
	{{1, 1, L6, KEY_D}, {0x222f}},
};

const Node Compose::NODE_1314734300496[] PROGMEM = {
	{{1, 1, L6, KEY_D}, {0x2230}},
};

const Node Compose::NODE_1314732638992[] PROGMEM = {
	{{0, 1, L1, KEY_G}, {0x25cc}},
	{{0, 1, L6, KEY_3}, {0x2234}},
	{{0, 1, L6, KEY_2}, {0x2235}},
	{{0, 1, L3, KEYPAD_8}, {0x21e1}},
	{{0, 0, L3, KEY_C}, {(uint16_t) NODE_1314734371952}},
	{{0, 1, L3, KEYPAD_2}, {0x21e3}},
	{{0, 0, L1, KEY_Z}, {(uint16_t) NODE_1314734372192}},
	{{0, 1, L3, KEYPAD_6}, {0x21e2}},
	{{0, 0, L1, KEY_MINUS}, {(uint16_t) NODE_1314734372432}},
	{{0, 1, L3, KEYPAD_4}, {0x21e0}},
	{{0, 0, L3, KEY_U}, {(uint16_t) NODE_1314734372672}},
	{{0, 0, L3, KEY_TILDE}, {(uint16_t) NODE_1314734372752}},
	{{0, 1, L3, KEY_S}, {0x22f0}},
	{{1, 1, L3, KEY_A}, {0x22f1}},
};

const Node Compose::NODE_1314734371952[] PROGMEM = {
	{{1, 1, L3, KEY_T}, {0x21e1}},
};

const Node Compose::NODE_1314734372192[] PROGMEM = {
	{{1, 1, L3, KEY_C}, {0x21e3}},
};

const Node Compose::NODE_1314734372432[] PROGMEM = {
	{{1, 1, L3, KEY_I}, {0x21e2}},
};

const Node Compose::NODE_1314734372672[] PROGMEM = {
	{{1, 1, L1, KEY_MINUS}, {0x21e0}},
};

const Node Compose::NODE_1314734372752[] PROGMEM = {
	{{1, 1, L3, KEYPAD_6}, {0x21e0}},
};

const Node Compose::NODE_1314732689104[] PROGMEM = {
	{{0, 1, L3, KEY_W}, {0x332}},
	{{0, 1, L1, KEY_0}, {0x2080}},
	{{0, 1, L1, KEY_1}, {0x2081}},
	{{0, 1, L1, KEY_2}, {0x2082}},
	{{0, 1, L1, KEY_3}, {0x2083}},
	{{0, 1, L1, KEY_4}, {0x2084}},
	{{0, 1, L1, KEY_5}, {0x2085}},
	{{0, 1, L1, KEY_6}, {0x2086}},
	{{0, 1, L1, KEY_7}, {0x2087}},
	{{0, 1, L1, KEY_8}, {0x2088}},
	{{0, 1, L1, KEY_9}, {0x2089}},
	{{0, 1, L3, KEY_N}, {0x208a}},
	{{0, 1, L3, KEY_O}, {0x208c}},
	{{0, 1, L3, KEY_J}, {0x208d}},
	{{0, 1, L3, KEY_K}, {0x208e}},
	{{0, 1, L3, KEY_PERIOD}, {0x2cc}},
	{{0, 1, L3, KEY_EQUAL}, {0x325}},
	{{0, 1, L4, KEY_EQUAL}, {0x324}},
	{{0, 1, L2, KEY_NON_US_NUM}, {0x330}},
	{{0, 1, L6, KEY_NON_US_NUM}, {0x32f}},
	{{0, 0, L1, KEY_TILDE}, {(uint16_t) NODE_1314733171840}},
	{{0, 1, L2, KEY_TILDE}, {0x32c}},
	{{0, 1, L1, KEY_H}, {0x33c}},
	{{0, 1, L3, KEY_C}, {0x329}},
	{{0, 1, L6, KEY_EQUAL}, {0x331}},
	{{0, 1, L1, KEY_A}, {0x31c}},
	{{0, 0, L3, KEY_TILDE}, {(uint16_t) NODE_1314733172560}},
	{{0, 1, L6, KEYPAD_0}, {0x33b}},
	{{0, 1, L3, KEY_E}, {0x230a}},
	{{0, 1, L3, KEY_R}, {0x230b}},
	{{0, 1, L6, KEY_D}, {0x2a1c}},
	{{0, 1, L3, KEY_G}, {0x2a31}},
	{{0, 1, L1, KEY_MINUS}, {0x208b}},
	{{0, 1, L1, KEY_R}, {0x2090}},
	{{0, 1, L1, KEY_F}, {0x2091}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x2095}},
	{{0, 1, L1, KEY_D}, {0x1d62}},
	{{0, 1, L1, KEY_Q}, {0x2c7c}},
	{{0, 1, L1, KEY_SLASH}, {0x2096}},
	{{0, 1, L1, KEY_W}, {0x2097}},
	{{0, 1, L1, KEY_J}, {0x2099}},
	{{0, 1, L1, KEY_G}, {0x2092}},
	{{0, 1, L1, KEY_N}, {0x209a}},
	{{0, 1, L1, KEY_S}, {0x1d63}},
	{{0, 1, L1, KEY_L}, {0x209b}},
	{{0, 1, L1, KEY_K}, {0x209c}},
	{{0, 1, L1, KEY_E}, {0x1d64}},
	{{0, 1, L1, KEY_Z}, {0x1d65}},
	{{0, 1, L1, KEY_X}, {0x2093}},
	{{0, 1, L5, KEY_U}, {0x1d66}},
	{{0, 1, L5, KEY_O}, {0x1d67}},
	{{0, 1, L5, KEY_S}, {0x1d68}},
	{{0, 1, L5, KEY_T}, {0x1d69}},
	{{1, 1, L5, KEY_A}, {0x1d6a}},
};

const Node Compose::NODE_1314733171840[] PROGMEM = {
	{{0, 1, L1, KEY_TILDE}, {0x32d}},
	{{0, 1, L2, KEY_I}, {0x1e12}},
	{{0, 1, L1, KEY_I}, {0x1e13}},
	{{0, 1, L2, KEY_W}, {0x1e3c}},
	{{0, 1, L1, KEY_W}, {0x1e3d}},
	{{0, 1, L2, KEY_J}, {0x1e4a}},
	{{0, 1, L1, KEY_J}, {0x1e4b}},
	{{0, 1, L2, KEY_K}, {0x1e70}},
	{{0, 1, L1, KEY_K}, {0x1e71}},
	{{0, 1, L2, KEY_F}, {0x1e18}},
	{{0, 1, L1, KEY_F}, {0x1e19}},
	{{0, 1, L2, KEY_E}, {0x1e76}},
	{{1, 1, L1, KEY_E}, {0x1e77}},
};

const Node Compose::NODE_1314733172560[] PROGMEM = {
	{{0, 1, L1, KEY_A}, {0x339}},
	{{0, 1, L3, KEY_R}, {0x33a}},
	{{1, 1, L3, KEY_E}, {0x32a}},
};

const Node Compose::NODE_1314732689344[] PROGMEM = {
	{{0, 1, L3, KEY_0}, {0x2bc}},
	{{1, 1, L1, KEY_J}, {0x149}},
};

const Node Compose::NODE_1314732693184[] PROGMEM = {
	{{0, 1, L2, KEY_SEMICOLON}, {0x126}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x127}},
	{{0, 1, L4, KEY_6}, {0x20a4}},
	{{0, 1, L3, KEY_N}, {0xb1}},
	{{0, 1, L2, KEY_W}, {0xa3}},
	{{0, 1, L1, KEY_W}, {0xa3}},
	{{0, 1, L2, KEY_P}, {0xa5}},
	{{0, 1, L1, KEY_P}, {0xa5}},
	{{0, 0, L1, KEY_MINUS}, {(uint16_t) NODE_1314733029104}},
	{{0, 1, L3, KEY_SEMICOLON}, {0xf7}},
	{{0, 1, L2, KEY_U}, {0x243}},
	{{0, 1, L2, KEY_D}, {0x197}},
	{{0, 1, L2, KEY_Q}, {0x248}},
	{{0, 1, L1, KEY_Q}, {0x249}},
	{{0, 1, L1, KEY_G}, {0x275}},
	{{0, 1, L2, KEY_G}, {0x19f}},
	{{0, 1, L2, KEY_N}, {0x2c63}},
	{{0, 0, L1, KEY_N}, {(uint16_t) NODE_1314733096480}},
	{{0, 1, L2, KEY_S}, {0x24c}},
	{{0, 1, L1, KEY_S}, {0x24d}},
	{{0, 1, L1, KEY_E}, {0x289}},
	{{0, 1, L2, KEY_E}, {0x244}},
	{{0, 1, L1, KEY_2}, {0x1bb}},
	{{0, 1, L5, KEY_D}, {0x1d7c}},
	{{0, 1, L5, KEY_P}, {0x1d7f}},
	{{0, 1, L3, KEY_C}, {0x22a3}},
	{{0, 1, L6, KEY_I}, {0x2a3a}},
	{{0, 1, L6, KEY_D}, {0x2a0d}},
	{{0, 1, L3, KEY_I}, {0x2192}},
	{{0, 1, L3, KEYPAD_6}, {0x27f6}},
	{{1, 1, L3, KEY_U}, {0x2919}},
};

const Node Compose::NODE_1314733029104[] PROGMEM = {
	{{0, 1, L1, KEY_PERIOD}, {0x2013}},
	{{1, 1, L1, KEY_MINUS}, {0x2014}},
};

const Node Compose::NODE_1314733096480[] PROGMEM = {
	{{1, 1, L1, KEY_SEMICOLON}, {0x210f}},
};

const Node Compose::NODE_1314732695024[] PROGMEM = {
	{{0, 1, L1, KEY_COMMA}, {0x218}},
	{{0, 1, L2, KEY_G}, {0xa7}},
	{{0, 1, L3, KEY_Y}, {0xa7}},
	{{0, 1, L2, KEY_L}, {0x1e9e}},
	{{0, 1, L2, KEY_H}, {0x2120}},
	{{0, 1, L1, KEY_H}, {0x2120}},
	{{1, 1, L2, KEY_SEMICOLON}, {0x1a9}},
};

const Node Compose::NODE_1314732695184[] PROGMEM = {
	{{0, 1, L1, KEY_COMMA}, {0x219}},
	{{0, 1, L1, KEY_K}, {0xfb06}},
	{{0, 1, L1, KEY_G}, {0xa7}},
	{{0, 1, L3, KEY_Y}, {0xa7}},
	{{0, 1, L1, KEY_L}, {0xdf}},
	{{0, 1, L2, KEY_H}, {0x2120}},
	{{0, 1, L1, KEY_H}, {0x2120}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x283}},
	{{0, 0, L1, KEY_E}, {(uint16_t) NODE_1314734303856}},
	{{1, 0, L1, KEY_A}, {(uint16_t) NODE_1314734448352}},
};

const Node Compose::NODE_1314734303856[] PROGMEM = {
	{{1, 1, L1, KEY_H}, {0x2211}},
};

const Node Compose::NODE_1314734448352[] PROGMEM = {
	{{0, 1, L1, KEY_O}, {0x210a}},
	{{0, 1, L2, KEY_SEMICOLON}, {0x210b}},
	{{0, 1, L2, KEY_D}, {0x2110}},
	{{0, 1, L2, KEY_W}, {0x2112}},
	{{0, 1, L1, KEY_W}, {0x2113}},
	{{0, 1, L2, KEY_N}, {0x2118}},
	{{0, 1, L2, KEY_S}, {0x211b}},
	{{0, 1, L2, KEY_U}, {0x212c}},
	{{0, 1, L1, KEY_F}, {0x212f}},
	{{0, 1, L2, KEY_F}, {0x2130}},
	{{0, 1, L2, KEY_M}, {0x2131}},
	{{0, 1, L2, KEY_H}, {0x2133}},
	{{1, 1, L1, KEY_G}, {0x2134}},
};

const Node Compose::NODE_1314732695264[] PROGMEM = {
	{{0, 1, L1, KEY_COMMA}, {0x21a}},
	{{0, 1, L2, KEY_H}, {0x2122}},
	{{0, 1, L1, KEY_H}, {0x2122}},
	{{0, 1, L1, KEY_W}, {0x1ae}},
	{{1, 1, L2, KEY_W}, {0x1ae}},
};

const Node Compose::NODE_1314732695424[] PROGMEM = {
	{{0, 1, L1, KEY_COMMA}, {0x21b}},
	{{0, 1, L1, KEY_H}, {0x2122}},
	{{0, 1, L2, KEY_H}, {0x2122}},
	{{0, 1, L1, KEY_W}, {0x288}},
	{{0, 1, L1, KEY_5}, {0x2e5}},
	{{0, 1, L1, KEY_4}, {0x2e6}},
	{{0, 1, L1, KEY_3}, {0x2e7}},
	{{0, 1, L1, KEY_2}, {0x2e8}},
	{{1, 1, L1, KEY_1}, {0x2e9}},
};

const Node Compose::NODE_1314732696624[] PROGMEM = {
	{{0, 1, L2, KEY_F}, {0x18f}},
	{{1, 1, L3, KEY_O}, {0x20ac}},
};

const Node Compose::NODE_1314732696704[] PROGMEM = {
	{{0, 1, L1, KEY_PERIOD}, {0x13f}},
	{{0, 1, L2, KEY_Q}, {0x1c7}},
	{{0, 1, L1, KEY_Q}, {0x1c8}},
	{{0, 1, L3, KEY_O}, {0x20a4}},
	{{0, 1, L1, KEY_MINUS}, {0xa3}},
	{{1, 1, L2, KEY_W}, {0x29f}},
};

const Node Compose::NODE_1314732696864[] PROGMEM = {
	{{0, 1, L1, KEY_PERIOD}, {0x140}},
	{{0, 1, L1, KEY_Q}, {0x1c9}},
	{{0, 1, L1, KEY_MINUS}, {0xa3}},
	{{0, 1, L1, KEY_W}, {0x26d}},
	{{1, 1, L1, KEY_LEFT_BRACE}, {0x26e}},
};

const Node Compose::NODE_1314732697584[] PROGMEM = {
	{{0, 1, L1, KEY_D}, {0x131}},
	{{0, 1, L1, KEY_Q}, {0x133}},
	{{0, 1, L3, KEY_H}, {0x294}},
	{{0, 0, L3, KEY_C}, {(uint16_t) NODE_1314733168880}},
	{{0, 1, L3, KEY_Y}, {0x1c3}},
	{{0, 1, L3, KEY_N}, {0x31f}},
	{{0, 1, L1, KEY_MINUS}, {0x320}},
	{{0, 0, L1, KEY_J}, {(uint16_t) NODE_1314734304016}},
	{{1, 1, L1, KEY_H}, {0x2111}},
};

const Node Compose::NODE_1314733168880[] PROGMEM = {
	{{0, 1, L1, KEY_SPACE}, {0x1c0}},
	{{1, 1, L3, KEY_C}, {0x1c1}},
};

const Node Compose::NODE_1314734304016[] PROGMEM = {
	{{1, 1, L1, KEY_K}, {0x222b}},
};

const Node Compose::NODE_1314732697664[] PROGMEM = {
	{{0, 1, L2, KEY_D}, {0x130}},
	{{0, 1, L2, KEY_Q}, {0x132}},
	{{0, 1, L1, KEY_Q}, {0x132}},
	{{1, 1, L1, KEY_H}, {0x2111}},
};

const Node Compose::NODE_1314732698704[] PROGMEM = {
	{{0, 1, L1, KEY_SEMICOLON}, {0x292}},
	{{0, 1, L1, KEY_LEFT_BRACE}, {0x292}},
	{{1, 1, L3, KEYPAD_6}, {0x21af}},
};

const Node Compose::NODE_1314732699024[] PROGMEM = {
	{{0, 1, L1, KEY_M}, {0xfb00}},
	{{0, 1, L1, KEY_D}, {0xfb01}},
	{{0, 1, L1, KEY_W}, {0xfb02}},
	{{0, 1, L1, KEY_L}, {0x17f}},
	{{1, 1, L2, KEY_L}, {0x17f}},
};

const Node Compose::NODE_1314732699344[] PROGMEM = {
	{{0, 1, L1, KEY_D}, {0xfb03}},
	{{0, 1, L1, KEY_W}, {0xfb04}},
	{{1, 1, L1, KEY_S}, {0x20a3}},
};

const Node Compose::NODE_1314732699584[] PROGMEM = {
	{{1, 1, L1, KEY_K}, {0xfb05}},
};

const Node Compose::NODE_1314732699984[] PROGMEM = {
	{{0, 1, L2, KEY_LEFT_BRACE}, {0x1f1}},
	{{0, 1, L1, KEY_LEFT_BRACE}, {0x1f2}},
	{{0, 1, L1, KEY_W}, {0x189}},
	{{1, 1, L2, KEY_W}, {0x189}},
};

const Node Compose::NODE_1314732700224[] PROGMEM = {
	{{0, 1, L1, KEY_LEFT_BRACE}, {0x1f3}},
	{{0, 0, L1, KEY_R}, {(uint16_t) NODE_1314732810512}},
	{{0, 1, L3, KEY_O}, {0x20ab}},
	{{1, 1, L1, KEY_W}, {0x256}},
};

const Node Compose::NODE_1314732810512[] PROGMEM = {
	{{1, 1, L1, KEY_O}, {0x2020}},
};

const Node Compose::NODE_1314732701104[] PROGMEM = {
	{{0, 1, L2, KEY_Q}, {0x1ca}},
	{{0, 1, L1, KEY_Q}, {0x1cb}},
	{{0, 1, L3, KEY_O}, {0x20a6}},
	{{0, 1, L1, KEY_G}, {0x2116}},
	{{0, 1, L2, KEY_G}, {0x2116}},
	{{0, 1, L2, KEY_F}, {0x18e}},
	{{0, 1, L2, KEY_J}, {0x274}},
	{{1, 1, L3, KEY_C}, {0x220}},
};

const Node Compose::NODE_1314732701344[] PROGMEM = {
	{{0, 1, L1, KEY_Q}, {0x1cc}},
	{{0, 1, L1, KEY_F}, {0x1dd}},
	{{0, 1, L1, KEY_W}, {0x273}},
	{{1, 1, L3, KEY_C}, {0x19e}},
};

const Node Compose::NODE_1314732702464[] PROGMEM = {
	{{0, 1, L3, KEY_Y}, {0x203c}},
	{{0, 1, L3, KEY_H}, {0x2047}},
	{{0, 1, L1, KEY_3}, {0x2154}},
	{{0, 1, L1, KEY_5}, {0x2156}},
	{{0, 1, L3, KEY_T}, {0xb2}},
	{{0, 1, L6, KEY_D}, {0x222c}},
	{{0, 1, L3, KEY_SEMICOLON}, {0x2237}},
	{{0, 1, L3, KEY_I}, {0x226b}},
	{{0, 1, L3, KEY_U}, {0x226a}},
	{{1, 1, L3, KEY_O}, {0x2a75}},
};

const Node Compose::NODE_1314732702384[] PROGMEM = {
	{{0, 1, L1, KEY_2}, {0x203c}},
	{{0, 1, L3, KEY_H}, {0x2049}},
	{{0, 1, L6, KEY_I}, {0x26a0}},
	{{1, 1, L3, KEY_Y}, {0xa1}},
};

const Node Compose::NODE_1314732702704[] PROGMEM = {
	{{0, 1, L1, KEY_2}, {0x2047}},
	{{0, 1, L3, KEY_Y}, {0x2048}},
	{{0, 1, L3, KEY_H}, {0xbf}},
	{{0, 1, L3, KEY_O}, {0x225f}},
	{{0, 1, L3, KEY_U}, {0x2a7b}},
	{{1, 1, L3, KEY_I}, {0x2a7c}},
};

const Node Compose::NODE_1314732703024[] PROGMEM = {
	{{0, 0, L3, KEY_H}, {(uint16_t) NODE_1314732703184}},
	{{0, 0, L3, KEY_Y}, {(uint16_t) NODE_1314732703104}},
	{{0, 0, L4, KEY_H}, {(uint16_t) NODE_1314732703344}},
	{{0, 0, L4, KEY_Y}, {(uint16_t) NODE_1314732703504}},
	{{0, 1, L1, KEY_3}, {0x2153}},
	{{0, 1, L1, KEY_5}, {0x2155}},
	{{0, 1, L1, KEY_6}, {0x2159}},
	{{0, 1, L1, KEY_8}, {0x215b}},
	{{0, 1, L3, KEY_S}, {0x215f}},
	{{0, 1, L1, KEY_4}, {0xbc}},
	{{0, 1, L1, KEY_2}, {0xbd}},
	{{0, 1, L1, KEY_7}, {0x2150}},
	{{0, 1, L1, KEY_9}, {0x2151}},
	{{0, 0, L1, KEY_1}, {(uint16_t) NODE_1314733082080}},
	{{1, 1, L3, KEY_T}, {0xb9}},
};

const Node Compose::NODE_1314732703184[] PROGMEM = {
	{{1, 1, L3, KEY_Y}, {0x203d}},
};

const Node Compose::NODE_1314732703104[] PROGMEM = {
	{{1, 1, L3, KEY_H}, {0x203d}},
};

const Node Compose::NODE_1314732703344[] PROGMEM = {
	{{1, 1, L4, KEY_Y}, {0x2e18}},
};

const Node Compose::NODE_1314732703504[] PROGMEM = {
	{{1, 1, L4, KEY_H}, {0x2e18}},
};

const Node Compose::NODE_1314733082080[] PROGMEM = {
	{{1, 1, L1, KEY_0}, {0x2152}},
};

const Node Compose::NODE_1314732703664[] PROGMEM = {
	{{1, 1, L2, KEYPAD_9}, {0x2021}},
};

const Node Compose::NODE_1314732802432[] PROGMEM = {
	{{1, 1, L5, KEY_SPACE}, {0x2d}},
};

const Node Compose::NODE_1314732802672[] PROGMEM = {
	{{0, 1, L1, KEY_7}, {0x204a}},
	{{1, 1, L1, KEY_8}, {0x215e}},
};

const Node Compose::NODE_1314732802592[] PROGMEM = {
	{{0, 0, L1, KEY_1}, {(uint16_t) NODE_1314732802832}},
	{{0, 1, L1, KEY_2}, {0x2161}},
	{{0, 1, L1, KEY_3}, {0x2162}},
	{{0, 1, L1, KEY_4}, {0x2163}},
	{{0, 1, L1, KEY_5}, {0x2164}},
	{{0, 1, L1, KEY_6}, {0x2165}},
	{{0, 1, L1, KEY_7}, {0x2166}},
	{{0, 1, L1, KEY_8}, {0x2167}},
	{{0, 1, L1, KEY_9}, {0x2168}},
	{{0, 1, L1, KEY_G}, {0xae}},
	{{0, 1, L2, KEY_G}, {0xae}},
	{{0, 1, L1, KEY_L}, {0x20a8}},
	{{0, 1, L3, KEY_O}, {0x20b9}},
	{{0, 1, L2, KEY_S}, {0x280}},
	{{1, 1, L1, KEY_F}, {0x211c}},
};

const Node Compose::NODE_1314732802832[] PROGMEM = {
	{{0, 1, L1, KEY_SPACE}, {0x2160}},
	{{0, 1, L1, KEY_0}, {0x2169}},
	{{0, 1, L1, KEY_1}, {0x216a}},
	{{1, 1, L1, KEY_2}, {0x216b}},
};

const Node Compose::NODE_1314732803872[] PROGMEM = {
	{{0, 0, L1, KEY_1}, {(uint16_t) NODE_1314732804032}},
	{{0, 1, L1, KEY_2}, {0x2171}},
	{{0, 1, L1, KEY_3}, {0x2172}},
	{{0, 1, L1, KEY_4}, {0x2173}},
	{{0, 1, L1, KEY_5}, {0x2174}},
	{{0, 1, L1, KEY_6}, {0x2175}},
	{{0, 1, L1, KEY_7}, {0x2176}},
	{{0, 1, L1, KEY_8}, {0x2177}},
	{{0, 1, L1, KEY_9}, {0x2178}},
	{{0, 1, L3, KEY_O}, {0x20b9}},
	{{0, 1, L3, KEY_W}, {0x27e}},
	{{0, 1, L1, KEY_S}, {0x27c}},
	{{1, 1, L1, KEY_F}, {0x211c}},
};

const Node Compose::NODE_1314732804032[] PROGMEM = {
	{{0, 1, L1, KEY_SPACE}, {0x2170}},
	{{0, 1, L1, KEY_0}, {0x2179}},
	{{0, 1, L1, KEY_1}, {0x217a}},
	{{1, 1, L1, KEY_2}, {0x217b}},
};

const Node Compose::NODE_1314732805312[] PROGMEM = {
	{{0, 1, L1, KEY_5}, {0x2157}},
	{{0, 1, L1, KEY_8}, {0x215c}},
	{{0, 1, L1, KEY_4}, {0xbe}},
	{{0, 1, L3, KEY_T}, {0xb3}},
	{{0, 1, L1, KEY_3}, {0x25c}},
	{{0, 1, L6, KEY_Z}, {0x221b}},
	{{0, 1, L6, KEY_D}, {0x222d}},
	{{0, 1, L3, KEY_I}, {0x22d9}},
	{{0, 1, L3, KEY_U}, {0x22d8}},
	{{1, 1, L3, KEY_O}, {0x2a76}},
};

const Node Compose::NODE_1314732805392[] PROGMEM = {
	{{0, 1, L1, KEY_5}, {0x2158}},
	{{0, 1, L6, KEY_Z}, {0x221c}},
	{{1, 1, L6, KEY_D}, {0x2a0c}},
};

const Node Compose::NODE_1314732805712[] PROGMEM = {
	{{0, 1, L1, KEY_6}, {0x215a}},
	{{1, 1, L1, KEY_8}, {0x215d}},
};

const Node Compose::NODE_1314732806592[] PROGMEM = {
	{{0, 1, L3, KEY_K}, {0x263a}},
	{{0, 1, L3, KEY_J}, {0x2639}},
	{{0, 1, L1, KEY_MINUS}, {0xf7}},
	{{0, 1, L3, KEY_SEMICOLON}, {0x2d0}},
	{{0, 1, L3, KEY_O}, {0x2254}},
	{{1, 1, L3, KEYPAD_6}, {0x29f4}},
};

const Node Compose::NODE_1314732806832[] PROGMEM = {
	{{0, 0, L3, KEY_S}, {(uint16_t) NODE_1314732806992}},
	{{0, 1, L3, KEY_O}, {0x20ac}},
	{{1, 1, L3, KEY_C}, {0xa2}},
};

const Node Compose::NODE_1314732806992[] PROGMEM = {
	{{1, 1, L1, KEY_G}, {0x2105}},
};

const Node Compose::NODE_1314732806912[] PROGMEM = {
	{{0, 1, L5, KEY_5}, {0x26a2}},
	{{1, 1, L5, KEY_4}, {0x26a4}},
};

const Node Compose::NODE_1314732807152[] PROGMEM = {
	{{0, 1, L5, KEY_4}, {0x26a3}},
	{{1, 1, L5, KEY_5}, {0x26a4}},
};

const Node Compose::NODE_1314732808272[] PROGMEM = {
	{{0, 1, L1, KEY_3}, {0x2665}},
	{{0, 1, L1, KEY_PERIOD}, {0x2235}},
	{{0, 1, L3, KEY_O}, {0x2264}},
	{{0, 1, L3, KEY_C}, {0x22b2}},
	{{0, 1, L3, KEY_U}, {0x226a}},
	{{0, 1, L3, KEY_K}, {0x2aa6}},
	{{0, 1, L3, KEY_H}, {0x2a7b}},
	{{0, 1, L3, KEY_I}, {0x2260}},
	{{0, 0, L3, KEY_NON_US_NUM}, {(uint16_t) NODE_1314734365152}},
	{{0, 1, L1, KEY_MINUS}, {0x2190}},
	{{1, 1, L3, KEYPAD_6}, {0x2194}},
};

const Node Compose::NODE_1314734365152[] PROGMEM = {
	{{1, 1, L3, KEY_NON_US_NUM}, {0x226e}},
};

const Node Compose::NODE_1314732808592[] PROGMEM = {
	{{0, 0, L2, KEY_J}, {(uint16_t) NODE_1314732808672}},
	{{0, 1, L1, KEY_G}, {0xa9}},
	{{0, 1, L2, KEY_G}, {0xa9}},
	{{0, 1, L2, KEY_F}, {0x20a0}},
	{{0, 1, L3, KEY_S}, {0x20a1}},
	{{0, 1, L1, KEY_S}, {0x20a2}},
	{{0, 1, L3, KEY_O}, {0x20ac}},
	{{0, 1, L3, KEY_C}, {0xa2}},
	{{1, 0, L2, KEY_A}, {(uint16_t) NODE_1314733080880}},
};

const Node Compose::NODE_1314732808672[] PROGMEM = {
	{{1, 1, L2, KEY_I}, {0x262e}},
};

const Node Compose::NODE_1314733080880[] PROGMEM = {
	{{1, 0, L2, KEY_A}, {(uint16_t) NODE_1314733081040}},
};

const Node Compose::NODE_1314733081040[] PROGMEM = {
	{{1, 1, L2, KEY_N}, {0x262d}},
};

const Node Compose::NODE_1314732808432[] PROGMEM = {
	{{0, 1, L3, KEY_R}, {0x25a1}},
	{{1, 1, L3, KEY_E}, {0x27e6}},
};

const Node Compose::NODE_1314732808832[] PROGMEM = {
	{{0, 1, L2, KEYPAD_7}, {0x2611}},
	{{1, 1, L2, KEYPAD_8}, {0x2612}},
};

const Node Compose::NODE_1314732808992[] PROGMEM = {
	{{1, 1, L6, KEYPAD_0}, {0x2611}},
};

const Node Compose::NODE_1314732809312[] PROGMEM = {
	{{1, 1, L6, KEYPAD_0}, {0x2612}},
};

const Node Compose::NODE_1314732809392[] PROGMEM = {
	{{0, 1, L3, KEY_Y}, {0x26a0}},
	{{0, 1, L3, KEY_O}, {0x225c}},
	{{0, 1, L3, KEY_N}, {0x2a39}},
	{{0, 1, L1, KEY_MINUS}, {0x2a3a}},
	{{1, 1, L3, KEY_G}, {0x2a3b}},
};

const Node Compose::NODE_1314732809792[] PROGMEM = {
	{{1, 1, L2, KEYPAD_0}, {0x237d}},
};

const Node Compose::NODE_1314732809872[] PROGMEM = {
	{{0, 1, L1, KEY_M}, {0x20b0}},
	{{0, 0, L1, KEY_G}, {(uint16_t) NODE_1314732810272}},
	{{0, 1, L3, KEY_Y}, {0xb6}},
	{{0, 1, L3, KEY_O}, {0x20bd}},
	{{0, 0, L1, KEY_S}, {(uint16_t) NODE_1314734304176}},
	{{1, 0, L1, KEY_SEMICOLON}, {(uint16_t) NODE_1314734451792}},
};

const Node Compose::NODE_1314732810272[] PROGMEM = {
	{{1, 1, L1, KEY_D}, {0x2318}},
};

const Node Compose::NODE_1314734304176[] PROGMEM = {
	{{1, 0, L1, KEY_G}, {(uint16_t) NODE_1314734304416}},
};

const Node Compose::NODE_1314734304416[] PROGMEM = {
	{{0, 1, L1, KEY_I}, {0x220f}},
	{{1, 1, L1, KEY_N}, {0x221d}},
};

const Node Compose::NODE_1314734451792[] PROGMEM = {
	{{0, 1, L1, KEY_SPACE}, {0x210e}},
	{{1, 1, L1, KEY_MINUS}, {0x210f}},
};

const Node Compose::NODE_1314732810832[] PROGMEM = {
	{{0, 0, L3, KEY_S}, {(uint16_t) NODE_1314732810992}},
	{{1, 1, L1, KEY_0}, {0x298}},
};

const Node Compose::NODE_1314732810992[] PROGMEM = {
	{{1, 1, L1, KEY_PERIOD}, {0x2052}},
};

const Node Compose::NODE_1314732811152[] PROGMEM = {
	{{1, 1, L2, KEY_PERIOD}, {0x2023}},
};

const Node Compose::NODE_1314733022464[] PROGMEM = {
	{{0, 1, L1, KEY_A}, {0xa9}},
	{{0, 1, L2, KEY_A}, {0xa9}},
	{{0, 1, L1, KEY_S}, {0xae}},
	{{0, 1, L2, KEY_S}, {0xae}},
	{{0, 1, L2, KEY_L}, {0xa7}},
	{{0, 1, L2, KEY_X}, {0xa4}},
	{{0, 1, L1, KEY_X}, {0xa4}},
	{{0, 1, L2, KEY_R}, {0x24b6}},
	{{0, 1, L2, KEY_F}, {0x152}},
	{{0, 0, L2, KEY_G}, {(uint16_t) NODE_1314733165760}},
	{{0, 1, L2, KEY_E}, {0x222}},
	{{1, 1, L1, KEY_G}, {0x2c7a}},
};

const Node Compose::NODE_1314733165760[] PROGMEM = {
	{{1, 1, L2, KEY_F}, {0x276}},
};

const Node Compose::NODE_1314733023344[] PROGMEM = {
	{{0, 1, L1, KEY_MINUS}, {0xb1}},
	{{1, 1, L6, KEY_I}, {0x2a39}},
};

const Node Compose::NODE_1314733023664[] PROGMEM = {
	{{0, 1, L3, KEY_Y}, {0xb6}},
	{{0, 1, L1, KEY_K}, {0x20a7}},
	{{0, 1, L3, KEY_O}, {0x20bd}},
	{{1, 1, L2, KEY_N}, {0xb6}},
};

const Node Compose::NODE_1314733024144[] PROGMEM = {
	{{0, 1, L2, KEY_A}, {0x20a1}},
	{{0, 1, L1, KEY_H}, {0x20a5}},
	{{0, 1, L1, KEY_A}, {0xa2}},
	{{0, 1, L2, KEY_R}, {0x23a}},
	{{0, 1, L1, KEY_R}, {0x2c65}},
	{{0, 1, L2, KEY_F}, {0x246}},
	{{0, 1, L1, KEY_F}, {0x247}},
	{{0, 1, L2, KEY_K}, {0x23e}},
	{{0, 1, L1, KEY_K}, {0x2c66}},
	{{0, 1, L5, KEY_W}, {0x19b}},
	{{0, 1, L3, KEY_RIGHT_BRACE}, {0x1e9c}},
	{{0, 1, L1, KEY_0}, {0x2205}},
	{{0, 1, L6, KEY_D}, {0x2a0f}},
	{{0, 1, L3, KEY_O}, {0x2260}},
	{{0, 1, L3, KEYPAD_4}, {0x219a}},
	{{0, 1, L3, KEYPAD_6}, {0x219b}},
	{{0, 1, L6, KEY_G}, {0x2209}},
	{{0, 1, L3, KEY_C}, {0x2224}},
	{{0, 1, L3, KEY_V}, {0x2241}},
	{{0, 1, L3, KEY_U}, {0x226e}},
	{{0, 1, L3, KEY_I}, {0x226f}},
	{{0, 1, L6, KEY_A}, {0x2284}},
	{{0, 1, L3, KEY_T}, {0x2197}},
	{{1, 1, L1, KEY_Z}, {0x2199}},
};

const Node Compose::NODE_1314733024544[] PROGMEM = {
	{{0, 1, L2, KEY_W}, {0x20a4}},
	{{0, 1, L2, KEY_J}, {0x20a6}},
	{{0, 1, L2, KEY_Y}, {0x20a9}},
	{{0, 1, L1, KEY_I}, {0x20ab}},
	{{0, 1, L2, KEY_A}, {0x20ac}},
	{{0, 1, L1, KEY_A}, {0x20ac}},
	{{0, 1, L2, KEY_F}, {0x20ac}},
	{{0, 1, L1, KEY_F}, {0x20ac}},
	{{0, 1, L2, KEY_N}, {0x20bd}},
	{{0, 1, L1, KEY_N}, {0x20bd}},
	{{0, 1, L2, KEY_S}, {0x20b9}},
	{{0, 1, L1, KEY_S}, {0x20b9}},
	{{0, 1, L2, KEY_P}, {0xa5}},
	{{0, 1, L1, KEY_P}, {0xa5}},
	{{0, 1, L1, KEY_W}, {0x2c61}},
	{{0, 0, L3, KEY_C}, {(uint16_t) NODE_1314733168480}},
	{{0, 1, L3, KEY_V}, {0x2245}},
	{{0, 1, L3, KEY_O}, {0x2261}},
	{{0, 1, L3, KEY_SEMICOLON}, {0x2255}},
	{{0, 1, L3, KEY_I}, {0x2265}},
	{{0, 1, L3, KEY_U}, {0x2264}},
	{{0, 1, L2, KEY_1}, {0x2257}},
	{{0, 1, L3, KEY_T}, {0x2259}},
	{{0, 1, L6, KEY_I}, {0x225c}},
	{{0, 1, L3, KEY_H}, {0x225f}},
	{{0, 1, L6, KEY_A}, {0x2286}},
	{{0, 1, L6, KEY_D}, {0x2a0e}},
	{{0, 0, L3, KEY_NON_US_NUM}, {(uint16_t) NODE_1314734362912}},
	{{0, 1, L3, KEYPAD_8}, {0x21de}},
	{{1, 1, L3, KEYPAD_2}, {0x21df}},
};

const Node Compose::NODE_1314733168480[] PROGMEM = {
	{{0, 1, L3, KEY_U}, {0x22b4}},
	{{1, 1, L3, KEY_I}, {0x22b5}},
};

const Node Compose::NODE_1314734362912[] PROGMEM = {
	{{1, 1, L3, KEY_NON_US_NUM}, {0x2260}},
};

const Node Compose::NODE_1314733024624[] PROGMEM = {
	{{0, 1, L3, KEY_S}, {0x20a5}},
	{{0, 1, L1, KEY_E}, {0xb5}},
	{{1, 0, L1, KEY_D}, {(uint16_t) NODE_1314734452272}},
};

const Node Compose::NODE_1314734452272[] PROGMEM = {
	{{1, 0, L1, KEY_A}, {(uint16_t) NODE_1314734452352}},
};

const Node Compose::NODE_1314734452352[] PROGMEM = {
	{{1, 0, L1, KEY_S}, {(uint16_t) NODE_1314734452192}},
};

const Node Compose::NODE_1314734452192[] PROGMEM = {
	{{1, 1, L1, KEY_G}, {0xb5}},
};

const Node Compose::NODE_1314733025264[] PROGMEM = {
	{{0, 1, L3, KEY_O}, {0x20a9}},
	{{0, 1, L2, KEY_P}, {0x1f7}},
	{{1, 1, L1, KEY_P}, {0x1f7}},
};

const Node Compose::NODE_1314733026224[] PROGMEM = {
	{{0, 1, L3, KEY_O}, {0x20ac}},
	{{1, 0, L1, KEY_W}, {(uint16_t) NODE_1314734448672}},
};

const Node Compose::NODE_1314734448672[] PROGMEM = {
	{{1, 1, L1, KEY_W}, {0x2113}},
};

const Node Compose::NODE_1314733027104[] PROGMEM = {
	{{0, 1, L2, KEY_A}, {0xa2}},
	{{0, 1, L1, KEY_A}, {0xa2}},
	{{0, 1, L3, KEY_U}, {0x22b2}},
	{{0, 1, L3, KEY_I}, {0x22b3}},
	{{0, 1, L1, KEY_SPACE}, {0x2223}},
	{{0, 1, L3, KEY_C}, {0x2016}},
	{{0, 1, L1, KEY_MINUS}, {0x22a2}},
	{{0, 1, L3, KEY_O}, {0x22a8}},
	{{0, 0, L3, KEY_G}, {(uint16_t) NODE_1314734362512}},
	{{0, 0, L3, KEY_NON_US_NUM}, {(uint16_t) NODE_1314734364512}},
	{{0, 1, L3, KEY_T}, {0x2191}},
	{{0, 1, L3, KEYPAD_6}, {0x21a6}},
	{{0, 1, L3, KEYPAD_4}, {0x21e4}},
	{{0, 0, L3, KEY_TILDE}, {(uint16_t) NODE_1314734368992}},
	{{0, 1, L3, KEYPAD_8}, {0x21d1}},
	{{0, 1, L3, KEYPAD_2}, {0x21d3}},
	{{0, 0, L3, KEY_A}, {(uint16_t) NODE_1314734370192}},
	{{0, 0, L3, KEY_S}, {(uint16_t) NODE_1314734370272}},
	{{0, 1, L2, KEY_SEMICOLON}, {0x210d}},
	{{0, 1, L2, KEY_J}, {0x2115}},
	{{0, 1, L2, KEY_N}, {0x2119}},
	{{0, 1, L2, KEY_T}, {0x211a}},
	{{0, 1, L2, KEY_S}, {0x211d}},
	{{0, 1, L2, KEY_LEFT_BRACE}, {0x2124}},
	{{0, 1, L5, KEY_O}, {0x213d}},
	{{0, 1, L5, KEY_N}, {0x213c}},
	{{0, 1, L6, KEY_N}, {0x213f}},
	{{0, 1, L6, KEY_L}, {0x2140}},
	{{0, 1, L3, KEY_J}, {0x2985}},
	{{0, 1, L3, KEY_K}, {0x2986}},
	{{0, 1, L3, KEY_E}, {0x27e6}},
	{{0, 1, L3, KEY_R}, {0x27e7}},
	{{1, 1, L3, KEY_F}, {0x2984}},
};

const Node Compose::NODE_1314734362512[] PROGMEM = {
	{{0, 1, L3, KEY_C}, {0x22c8}},
	{{1, 1, L1, KEY_SPACE}, {0x22c9}},
};

const Node Compose::NODE_1314734364512[] PROGMEM = {
	{{1, 1, L3, KEY_NON_US_NUM}, {0x2224}},
};

const Node Compose::NODE_1314734368992[] PROGMEM = {
	{{1, 1, L3, KEYPAD_6}, {0x21e4}},
};

const Node Compose::NODE_1314734370192[] PROGMEM = {
	{{0, 1, L3, KEY_T}, {0x21d6}},
	{{1, 1, L1, KEY_Z}, {0x21d8}},
};

const Node Compose::NODE_1314734370272[] PROGMEM = {
	{{0, 1, L3, KEY_T}, {0x21d7}},
	{{1, 1, L1, KEY_Z}, {0x21d9}},
};

const Node Compose::NODE_1314733027904[] PROGMEM = {
	{{0, 1, L3, KEY_O}, {0xa5}},
	{{0, 1, L1, KEY_MINUS}, {0xa5}},
	{{0, 1, L2, KEY_P}, {0x28f}},
	{{0, 1, L2, KEY_O}, {0x21c}},
	{{1, 1, L1, KEY_O}, {0x21c}},
};

const Node Compose::NODE_1314733028144[] PROGMEM = {
	{{0, 1, L3, KEY_O}, {0xa5}},
	{{0, 1, L1, KEY_MINUS}, {0xa5}},
	{{1, 1, L1, KEY_O}, {0x21d}},
};

const Node Compose::NODE_1314733028864[] PROGMEM = {
	{{1, 0, L1, KEY_M}, {(uint16_t) NODE_1314733029184}},
};

const Node Compose::NODE_1314733029184[] PROGMEM = {
	{{1, 1, L1, KEY_L}, {0x1e9b}},
};

const Node Compose::NODE_1314733029504[] PROGMEM = {
	{{0, 1, L1, KEY_T}, {0x2669}},
	{{0, 1, L1, KEY_F}, {0x266a}},
	{{0, 1, L2, KEY_F}, {0x266b}},
	{{0, 1, L2, KEY_L}, {0x266c}},
	{{0, 1, L1, KEY_U}, {0x266d}},
	{{0, 1, L1, KEY_M}, {0x266e}},
	{{1, 1, L3, KEY_Z}, {0x266f}},
};

const Node Compose::NODE_1314733030704[] PROGMEM = {
	{{0, 1, L1, KEY_G}, {0xa4}},
	{{0, 1, L2, KEY_G}, {0xa4}},
	{{0, 1, L3, KEY_W}, {0x264}},
	{{1, 1, L3, KEY_H}, {0x242}},
};

const Node Compose::NODE_1314733030944[] PROGMEM = {
	{{0, 1, L1, KEY_G}, {0xa4}},
	{{0, 1, L2, KEY_G}, {0xa4}},
	{{1, 1, L3, KEY_H}, {0x241}},
};

const Node Compose::NODE_1314733081520[] PROGMEM = {
	{{0, 1, L1, KEY_F}, {0xe6}},
	{{0, 1, L1, KEY_R}, {0x251}},
	{{0, 1, L1, KEY_0}, {0x660}},
	{{0, 1, L1, KEY_1}, {0x661}},
	{{0, 1, L1, KEY_2}, {0x662}},
	{{0, 1, L1, KEY_3}, {0x663}},
	{{0, 1, L1, KEY_4}, {0x664}},
	{{0, 1, L1, KEY_5}, {0x665}},
	{{0, 1, L1, KEY_6}, {0x666}},
	{{0, 1, L1, KEY_7}, {0x667}},
	{{0, 1, L1, KEY_8}, {0x668}},
	{{0, 1, L1, KEY_9}, {0x669}},
	{{1, 1, L1, KEY_X}, {0x221d}},
};

const Node Compose::NODE_1314733081600[] PROGMEM = {
	{{1, 1, L2, KEY_F}, {0xc6}},
};

const Node Compose::NODE_1314733082320[] PROGMEM = {
	{{0, 1, L1, KEY_3}, {0x2189}},
	{{0, 1, L1, KEY_PERIOD}, {0x298}},
	{{1, 0, L3, KEY_NON_US_NUM}, {(uint16_t) NODE_1314734309136}},
};

const Node Compose::NODE_1314734309136[] PROGMEM = {
	{{1, 1, L3, KEY_NON_US_NUM}, {0x2205}},
};

const Node Compose::NODE_1314733082640[] PROGMEM = {
	{{0, 1, L1, KEY_0}, {0x2070}},
	{{0, 0, L3, KEY_W}, {(uint16_t) NODE_1314733082560}},
	{{0, 1, L1, KEY_2}, {0xb2}},
	{{0, 1, L1, KEY_3}, {0xb3}},
	{{0, 1, L1, KEY_1}, {0xb9}},
	{{0, 1, L1, KEY_4}, {0x2074}},
	{{0, 1, L1, KEY_5}, {0x2075}},
	{{0, 1, L1, KEY_6}, {0x2076}},
	{{0, 1, L1, KEY_7}, {0x2077}},
	{{0, 1, L1, KEY_8}, {0x2078}},
	{{0, 1, L1, KEY_9}, {0x2079}},
	{{0, 1, L3, KEY_N}, {0x207a}},
	{{0, 1, L3, KEY_O}, {0x207c}},
	{{0, 1, L3, KEY_J}, {0x207d}},
	{{0, 1, L3, KEY_K}, {0x207e}},
	{{0, 1, L3, KEY_G}, {0x33d}},
	{{0, 1, L3, KEY_E}, {0x2308}},
	{{0, 1, L3, KEY_R}, {0x2309}},
	{{0, 0, L3, KEY_C}, {(uint16_t) NODE_1314734367392}},
	{{0, 0, L3, KEY_A}, {(uint16_t) NODE_1314734367952}},
	{{0, 1, L3, KEY_I}, {0x20d7}},
	{{0, 1, L3, KEYPAD_6}, {0x20d7}},
	{{0, 1, L3, KEY_U}, {0x20d6}},
	{{0, 1, L3, KEYPAD_4}, {0x20d6}},
	{{0, 0, L3, KEY_TILDE}, {(uint16_t) NODE_1314734442032}},
	{{0, 1, L1, KEY_MINUS}, {0x207b}},
	{{0, 1, L1, KEY_R}, {0x1d43}},
	{{0, 1, L1, KEY_U}, {0x1d47}},
	{{0, 1, L1, KEY_A}, {0x1d9c}},
	{{0, 1, L1, KEY_I}, {0x1d48}},
	{{0, 1, L1, KEY_F}, {0x1d49}},
	{{0, 1, L1, KEY_M}, {0x1da0}},
	{{0, 1, L1, KEY_O}, {0x1d4d}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x2b0}},
	{{0, 1, L1, KEY_D}, {0x2071}},
	{{0, 1, L1, KEY_Q}, {0x2b2}},
	{{0, 1, L1, KEY_SLASH}, {0x1d4f}},
	{{0, 1, L1, KEY_W}, {0x2e1}},
	{{0, 1, L1, KEY_H}, {0x1d50}},
	{{0, 1, L1, KEY_J}, {0x207f}},
	{{0, 1, L1, KEY_G}, {0x1d52}},
	{{0, 1, L1, KEY_N}, {0x1d56}},
	{{0, 1, L1, KEY_S}, {0x2b3}},
	{{0, 1, L1, KEY_L}, {0x2e2}},
	{{0, 1, L1, KEY_K}, {0x1d57}},
	{{0, 1, L1, KEY_E}, {0x1d58}},
	{{0, 1, L1, KEY_Z}, {0x1d5b}},
	{{0, 1, L1, KEY_Y}, {0x2b7}},
	{{0, 1, L1, KEY_X}, {0x2e3}},
	{{0, 1, L1, KEY_P}, {0x2b8}},
	{{0, 1, L1, KEY_LEFT_BRACE}, {0x1dbb}},
	{{0, 1, L2, KEY_R}, {0x1d2c}},
	{{0, 1, L2, KEY_U}, {0x1d2e}},
	{{0, 1, L2, KEY_I}, {0x1d30}},
	{{0, 1, L2, KEY_F}, {0x1d31}},
	{{0, 1, L2, KEY_O}, {0x1d33}},
	{{0, 1, L2, KEY_SEMICOLON}, {0x1d34}},
	{{0, 1, L2, KEY_D}, {0x1d35}},
	{{0, 1, L2, KEY_Q}, {0x1d36}},
	{{0, 1, L2, KEY_SLASH}, {0x1d37}},
	{{0, 1, L2, KEY_W}, {0x1d38}},
	{{0, 1, L2, KEY_H}, {0x1d39}},
	{{0, 1, L2, KEY_J}, {0x1d3a}},
	{{0, 1, L2, KEY_G}, {0x1d3c}},
	{{0, 1, L2, KEY_N}, {0x1d3e}},
	{{0, 1, L2, KEY_S}, {0x1d3f}},
	{{0, 1, L2, KEY_K}, {0x1d40}},
	{{0, 1, L2, KEY_E}, {0x1d41}},
	{{0, 1, L2, KEY_Z}, {0x2c7d}},
	{{0, 1, L2, KEY_Y}, {0x1d42}},
	{{0, 1, L5, KEY_R}, {0x1d45}},
	{{0, 1, L5, KEY_U}, {0x1d5d}},
	{{0, 1, L5, KEY_O}, {0x1d5e}},
	{{0, 1, L5, KEY_I}, {0x1d5f}},
	{{0, 1, L5, KEY_F}, {0x1d4b}},
	{{0, 1, L5, KEY_T}, {0x1d60}},
	{{0, 1, L5, KEY_A}, {0x1d61}},
	{{0, 1, L5, KEY_Q}, {0x1dbf}},
	{{1, 1, L5, KEY_P}, {0x1db7}},
};

const Node Compose::NODE_1314733082560[] PROGMEM = {
	{{0, 1, L1, KEY_D}, {0x2071}},
	{{1, 1, L1, KEY_J}, {0x207f}},
};

const Node Compose::NODE_1314734367392[] PROGMEM = {
	{{1, 1, L1, KEY_Z}, {0x2195}},
};

const Node Compose::NODE_1314734367952[] PROGMEM = {
	{{1, 1, L1, KEY_Z}, {0x2921}},
};

const Node Compose::NODE_1314734442032[] PROGMEM = {
	{{1, 1, L3, KEYPAD_6}, {0x20d6}},
};

const Node Compose::NODE_1314733091520[] PROGMEM = {
	{{1, 1, L5, KEY_O}, {0x263}},
};

const Node Compose::NODE_1314733092240[] PROGMEM = {
	{{1, 1, L3, KEY_K}, {0x1b2}},
};

const Node Compose::NODE_1314733092080[] PROGMEM = {
	{{0, 1, L3, KEY_K}, {0x28b}},
	{{0, 1, L3, KEY_C}, {0x2193}},
	{{1, 0, L3, KEY_S}, {(uint16_t) NODE_1314734368032}},
};

const Node Compose::NODE_1314734368032[] PROGMEM = {
	{{1, 1, L3, KEY_T}, {0x2922}},
};

const Node Compose::NODE_1314733093040[] PROGMEM = {
	{{0, 1, L2, KEY_J}, {0x19d}},
	{{0, 1, L1, KEY_J}, {0x272}},
	{{1, 1, L1, KEY_M}, {0x284}},
};

const Node Compose::NODE_1314733093200[] PROGMEM = {
	{{1, 1, L2, KEY_J}, {0x19d}},
};

const Node Compose::NODE_1314733093680[] PROGMEM = {
	{{1, 0, L1, KEY_SEMICOLON}, {(uint16_t) NODE_1314733093840}},
};

const Node Compose::NODE_1314733093840[] PROGMEM = {
	{{0, 1, L1, KEY_Q}, {0x267}},
	{{1, 1, L1, KEY_O}, {0x267}},
};

const Node Compose::NODE_1314733163920[] PROGMEM = {
	{{0, 1, L2, KEY_SEMICOLON}, {0x1b7}},
	{{1, 1, L2, KEY_LEFT_BRACE}, {0x1b7}},
};

const Node Compose::NODE_1314733165040[] PROGMEM = {
	{{1, 1, L2, KEY_U}, {0x299}},
};

const Node Compose::NODE_1314733165120[] PROGMEM = {
	{{0, 1, L2, KEY_O}, {0x262}},
	{{1, 1, L2, KEY_E}, {0x222}},
};

const Node Compose::NODE_1314733165280[] PROGMEM = {
	{{0, 1, L2, KEY_SEMICOLON}, {0x29c}},
	{{0, 1, L2, KEY_Z}, {0x1f6}},
	{{1, 1, L1, KEY_Z}, {0x1f6}},
};

const Node Compose::NODE_1314733165920[] PROGMEM = {
	{{1, 1, L5, KEY_R}, {0x251}},
};

const Node Compose::NODE_1314733166080[] PROGMEM = {
	{{1, 1, L5, KEY_F}, {0x25b}},
};

const Node Compose::NODE_1314733166240[] PROGMEM = {
	{{1, 1, L5, KEY_T}, {0x278}},
};

const Node Compose::NODE_1314733166400[] PROGMEM = {
	{{1, 1, L5, KEY_P}, {0x28a}},
};

const Node Compose::NODE_1314733167840[] PROGMEM = {
	{{0, 1, L1, KEY_O}, {0x261}},
	{{0, 1, L2, KEY_E}, {0x222}},
	{{1, 1, L1, KEY_E}, {0x223}},
};

const Node Compose::NODE_1314733168400[] PROGMEM = {
	{{0, 0, L1, KEY_3}, {(uint16_t) NODE_1314733168560}},
	{{0, 1, L3, KEY_I}, {0x2aa7}},
	{{1, 1, L3, KEY_J}, {0x2985}},
};

const Node Compose::NODE_1314733168560[] PROGMEM = {
	{{1, 1, L1, KEY_SPACE}, {0x25e}},
};

const Node Compose::NODE_1314733169200[] PROGMEM = {
	{{1, 1, L3, KEY_PERIOD}, {0x2c8}},
};

const Node Compose::NODE_1314733172960[] PROGMEM = {
	{{0, 1, L1, KEY_NON_US_NUM}, {0x1dc4}},
	{{1, 1, L1, KEY_EQUAL}, {0x1dc6}},
};

const Node Compose::NODE_1314733173040[] PROGMEM = {
	{{0, 1, L6, KEY_EQUAL}, {0x1dc5}},
	{{1, 0, L1, KEY_NON_US_NUM}, {(uint16_t) NODE_1314733173520}},
};

const Node Compose::NODE_1314733173520[] PROGMEM = {
	{{1, 1, L1, KEY_EQUAL}, {0x1dc8}},
};

const Node Compose::NODE_1314733173200[] PROGMEM = {
	{{0, 1, L6, KEY_EQUAL}, {0x1dc7}},
	{{1, 0, L1, KEY_EQUAL}, {(uint16_t) NODE_1314733173680}},
};

const Node Compose::NODE_1314733173680[] PROGMEM = {
	{{1, 1, L1, KEY_NON_US_NUM}, {0x1dc9}},
};

const Node Compose::NODE_1314734296416[] PROGMEM = {
	{{1, 1, L5, KEY_P}, {0x223}},
};

const Node Compose::NODE_1314734298016[] PROGMEM = {
	{{0, 1, L1, KEY_Z}, {0x195}},
	{{0, 1, L1, KEY_R}, {0x2135}},
	{{0, 1, L1, KEY_U}, {0x2136}},
	{{0, 1, L1, KEY_O}, {0x2137}},
	{{1, 1, L1, KEY_I}, {0x2138}},
};

const Node Compose::NODE_1314734298336[] PROGMEM = {
	{{0, 1, L1, KEY_P}, {0x1bf}},
	{{0, 0, L1, KEY_D}, {(uint16_t) NODE_1314734369792}},
	{{0, 1, L1, KEY_N}, {0x2118}},
	{{0, 1, L2, KEY_1}, {0xb0}},
	{{0, 1, L3, KEY_PERIOD}, {0x2032}},
	{{0, 1, L1, KEY_3}, {0x2034}},
	{{1, 1, L1, KEY_4}, {0x2057}},
};

const Node Compose::NODE_1314734369792[] PROGMEM = {
	{{1, 1, L1, KEY_I}, {0x21af}},
};

const Node Compose::NODE_1314734298736[] PROGMEM = {
	{{0, 1, L1, KEY_3}, {0x221b}},
	{{1, 1, L1, KEY_4}, {0x221c}},
};

const Node Compose::NODE_1314734299216[] PROGMEM = {
	{{0, 1, L1, KEY_2}, {0x222c}},
	{{0, 1, L6, KEY_D}, {0x222c}},
	{{0, 1, L1, KEY_3}, {0x222d}},
	{{0, 1, L1, KEY_4}, {0x2a0c}},
	{{0, 1, L3, KEY_O}, {0x2a0e}},
	{{0, 1, L3, KEY_G}, {0x2a18}},
	{{0, 1, L6, KEY_B}, {0x2a19}},
	{{1, 1, L6, KEY_C}, {0x2a1a}},
};

const Node Compose::NODE_1314734300896[] PROGMEM = {
	{{0, 1, L1, KEY_PERIOD}, {0x2234}},
	{{0, 1, L3, KEY_O}, {0x2265}},
	{{0, 1, L3, KEY_I}, {0x226b}},
	{{0, 1, L3, KEY_H}, {0x2a7c}},
	{{0, 0, L3, KEY_NON_US_NUM}, {(uint16_t) NODE_1314734365472}},
	{{0, 1, L3, KEYPAD_6}, {0x21a3}},
	{{1, 1, L1, KEY_MINUS}, {0x291a}},
};

const Node Compose::NODE_1314734365472[] PROGMEM = {
	{{1, 1, L3, KEY_NON_US_NUM}, {0x226f}},
};

const Node Compose::NODE_1314734301456[] PROGMEM = {
	{{0, 1, L3, KEY_O}, {0x2245}},
	{{0, 1, L3, KEY_V}, {0x2248}},
	{{1, 0, L3, KEY_NON_US_NUM}, {(uint16_t) NODE_1314734364832}},
};

const Node Compose::NODE_1314734364832[] PROGMEM = {
	{{1, 1, L3, KEY_NON_US_NUM}, {0x2241}},
};

const Node Compose::NODE_1314734302976[] PROGMEM = {
	{{0, 1, L3, KEY_O}, {0x2257}},
	{{0, 1, L2, KEY_A}, {0x2103}},
	{{1, 1, L2, KEY_M}, {0x2109}},
};

const Node Compose::NODE_1314734305136[] PROGMEM = {
	{{0, 1, L6, KEY_G}, {0x220b}},
	{{1, 0, L3, KEY_NON_US_NUM}, {(uint16_t) NODE_1314734363952}},
};

const Node Compose::NODE_1314734363952[] PROGMEM = {
	{{1, 1, L3, KEY_NON_US_NUM}, {0x2209}},
};

const Node Compose::NODE_1314734306016[] PROGMEM = {
	{{0, 1, L3, KEY_W}, {0x22bb}},
	{{1, 1, L6, KEY_2}, {0x22c1}},
};

const Node Compose::NODE_1314734306256[] PROGMEM = {
	{{0, 1, L3, KEY_W}, {0x2a5f}},
	{{1, 1, L6, KEY_3}, {0x22c0}},
};

const Node Compose::NODE_1314734306496[] PROGMEM = {
	{{0, 1, L6, KEY_C}, {0x22c3}},
	{{1, 1, L6, KEY_D}, {0x2a1a}},
};

const Node Compose::NODE_1314734306656[] PROGMEM = {
	{{0, 1, L6, KEY_B}, {0x22c2}},
	{{1, 1, L6, KEY_D}, {0x2a19}},
};

const Node Compose::NODE_1314734306576[] PROGMEM = {
	{{1, 1, L6, KEY_L}, {0x2211}},
};

const Node Compose::NODE_1314734306896[] PROGMEM = {
	{{1, 1, L6, KEY_N}, {0x220f}},
};

const Node Compose::NODE_1314734307216[] PROGMEM = {
	{{0, 1, L3, KEY_O}, {0x2286}},
	{{1, 0, L3, KEY_NON_US_NUM}, {(uint16_t) NODE_1314734365712}},
};

const Node Compose::NODE_1314734365712[] PROGMEM = {
	{{1, 1, L3, KEY_NON_US_NUM}, {0x2284}},
};

const Node Compose::NODE_1314734308656[] PROGMEM = {
	{{0, 1, L3, KEY_A}, {0x2216}},
	{{0, 1, L3, KEY_T}, {0x2196}},
	{{1, 1, L1, KEY_Z}, {0x2198}},
};

const Node Compose::NODE_1314734309296[] PROGMEM = {
	{{0, 1, L3, KEY_G}, {0x2217}},
	{{0, 1, L6, KEY_I}, {0x2a3b}},
	{{0, 1, L6, KEY_D}, {0x2a18}},
	{{1, 1, L3, KEY_C}, {0x22ca}},
};

const Node Compose::NODE_1314734367312[] PROGMEM = {
	{{0, 1, L3, KEY_I}, {0x2194}},
	{{0, 1, L3, KEY_C}, {0x21a4}},
	{{0, 1, L3, KEYPAD_6}, {0x21c6}},
	{{0, 1, L3, KEYPAD_4}, {0x21c7}},
	{{0, 1, L1, KEY_MINUS}, {0x27f5}},
	{{1, 1, L3, KEY_U}, {0x21a2}},
};

const Node Compose::NODE_1314734368352[] PROGMEM = {
	{{0, 1, L3, KEY_C}, {0x21a5}},
	{{0, 1, L3, KEYPAD_2}, {0x21c5}},
	{{1, 1, L3, KEYPAD_8}, {0x21c8}},
};

const Node Compose::NODE_1314734368592[] PROGMEM = {
	{{0, 1, L3, KEY_C}, {0x21a7}},
	{{0, 1, L3, KEYPAD_2}, {0x21ca}},
	{{1, 1, L3, KEYPAD_8}, {0x21f5}},
};

const Node Compose::NODE_1314734368672[] PROGMEM = {
	{{0, 1, L3, KEY_C}, {0x21e5}},
	{{0, 1, L3, KEYPAD_4}, {0x21c4}},
	{{1, 1, L3, KEYPAD_6}, {0x21c9}},
};

const Node Compose::NODE_1314734373152[] PROGMEM = {
	{{1, 0, L3, KEYPAD_6}, {(uint16_t) NODE_1314734373312}},
};

const Node Compose::NODE_1314734373312[] PROGMEM = {
	{{0, 1, L1, KEY_MINUS}, {0x27f5}},
	{{1, 1, L3, KEY_U}, {0x21a2}},
};

const Node Compose::NODE_1314734450592[] PROGMEM = {
	{{1, 1, L3, KEY_K}, {0x2986}},
};

const Node Compose::NODE_1314734450992[] PROGMEM = {
	{{1, 1, L3, KEY_R}, {0x27e7}},
};

const Node Compose::NODE_1314734451312[] PROGMEM = {
	{{1, 1, L3, KEY_F}, {0x2984}},
};


/*
 * Mapping of Keys which exist multiple times on keyboard
 * left Sequence will be remapped right sequence for lookup
*/
const LayeredKey Compose::aliases[][2] {
	{{L3, KEY_L}, {L1, KEY_MINUS}},
	{{L1, KEYPAD_SUBTRACT}, {L1, KEY_MINUS}},
	{{L1, KEYPAD_1}, {L1, KEY_1}},
	{{L1, KEYPAD_2}, {L1, KEY_2}},
	{{L1, KEYPAD_3}, {L1, KEY_3}},
	{{L1, KEYPAD_4}, {L1, KEY_4}},
	{{L1, KEYPAD_5}, {L1, KEY_5}},
	{{L1, KEYPAD_6}, {L1, KEY_6}},
	{{L1, KEYPAD_7}, {L1, KEY_7}},
	{{L1, KEYPAD_8}, {L1, KEY_8}},
	{{L1, KEYPAD_9}, {L1, KEY_9}},
	{{L1, KEYPAD_0}, {L1, KEY_0}},
	{{L1, KEYPAD_DIVIDE}, {L3, KEY_S}},
	{{L1, KEYPAD_MULTIPLY}, {L3, KEY_G}},
	{{L1, KEYPAD_ADD}, {L3, KEY_N}},
	{{L3, KEY_NUM_LOCK}, {L3, KEY_O}},
};

LayeredKey Compose::getAlias(uint8_t layer, uint8_t key) {
	for(int16_t i = 0; i < (sizeof(aliases) / sizeof(aliases[0])); i++){
		if(layer == aliases[i][0].layer && key == aliases[i][0].key){
			return aliases[i][1];
		}
	}
	return {0,0};
}

uint16_t Compose::transition(uint8_t layer, uint8_t key) {
	Node* cur = currentNode;
	Node val_cur;
	
	LayeredKey alias = getAlias(layer, key);
	if(alias.layer != 0 && alias.key != 0){
		layer = alias.layer;
		key = alias.key;
	}
	
	do {
		memcpy_P(&val_cur, cur, sizeof(val_cur));
		if (val_cur.layeredKey.layer == layer && val_cur.layeredKey.keycode == key) { //found
			if (val_cur.layeredKey.isLeaf) {
				currentNode = const_cast<Node*>(root);
				return val_cur.payload.unicode;
				
			} else { //found, waiting for next key
				currentNode = const_cast<Node*>(val_cur.payload.nodes);
				return 1;
			}
		}
		cur++;
	} while (val_cur.layeredKey.isLastElement == 0);
	
	//not found
	currentNode = const_cast<Node*>(root);
	return 0;
}

void Compose::reset(){
	currentNode = const_cast<Node*>(root);
}